// apps/preview-svelte/src/svelte/badge-spinner.svelte
<script lang="ts">
	import { Badge } from "@/svelte-ui/badge/index.js";
	import { Spinner } from "@/svelte-ui/spinner/index.js";
</script>

<div class="flex flex-wrap gap-2">
	<Badge variant="destructive">
		<Spinner data-icon="inline-start" />
		Deleting
	</Badge>
	<Badge variant="secondary">
		Generating
		<Spinner data-icon="inline-end" />
	</Badge>
</div>

// apps/preview-vue/src/vue/badge-spinner.vue
<script setup lang="ts">
import { Badge } from '@/ui/badge'
import { Spinner } from '@/ui/spinner'
</script>

<template>
  <div class="flex flex-wrap gap-2">
    <Badge variant="destructive">
      <Spinner data-icon="inline-start" />
      Deleting
    </Badge>
    <Badge variant="secondary">
      Generating
      <Spinner data-icon="inline-end" />
    </Badge>
  </div>
</template>
