// apps/preview-svelte/src/svelte/button-demo.svelte
<script lang="ts">
	import ArrowUpIcon from "~icons/ms/arrow_upward";
	import { Button } from "@/svelte-ui/button/index.js";
</script>

<div class="flex flex-wrap items-center gap-2 md:flex-row">
	<Button variant="outline">Button</Button>
	<Button variant="outline" size="icon" aria-label="Submit">
		<ArrowUpIcon />
	</Button>
</div>

// apps/preview-vue/src/vue/button-demo.vue
<script setup lang="ts">
import ArrowUpIcon from "@material-symbols/svg-400/rounded/arrow_upward.svg?component"
import { Button } from '@/ui/button'
</script>

<template>
  <div class="flex flex-wrap items-center gap-2 md:flex-row">
    <Button variant="outline">
      Button
    </Button>
    <Button variant="outline" size="icon" aria-label="Submit">
      <ArrowUpIcon />
    </Button>
  </div>
</template>
