// apps/v4/examples/ark/input-invalid.tsx
import { Field, FieldDescription, FieldLabel } from "@/examples/ark/ui/field"
import { Input } from "@/examples/ark/ui/input"

export function InputInvalid() {
  return (
    <Field data-invalid>
      <FieldLabel htmlFor="input-invalid">Invalid Input</FieldLabel>
      <Input id="input-invalid" placeholder="Error" aria-invalid />
      <FieldDescription>
        This field contains validation errors.
      </FieldDescription>
    </Field>
  )
}

// apps/preview-vue/src/vue/input-invalid.vue
<script setup lang="ts">
import {
  Field,
  FieldDescription,
  FieldLabel,
} from '@/ui/field'
import { Input } from '@/ui/input'
</script>

<template>
  <Field data-invalid>
    <FieldLabel for="input-invalid">Invalid Input</FieldLabel>
    <Input id="input-invalid" placeholder="Error" aria-invalid />
    <FieldDescription>
      This field contains validation errors.
    </FieldDescription>
  </Field>
</template>
