// apps/preview-svelte/src/svelte/input-group-kbd.svelte
<script lang="ts">
	import * as Kbd from "@/svelte-ui/kbd/index.js";
	import * as InputGroup from "@/svelte-ui/input-group/index.js";
	import SearchIcon from "~icons/ms/search";
</script>

<div class="flex w-full max-w-xs flex-col gap-6">
	<InputGroup.Root>
		<InputGroup.Input placeholder="Search..." />
		<InputGroup.Addon>
			<SearchIcon />
		</InputGroup.Addon>
		<InputGroup.Addon align="inline-end">
			<Kbd.Root>⌘</Kbd.Root>
			<Kbd.Root>K</Kbd.Root>
		</InputGroup.Addon>
	</InputGroup.Root>
</div>

// apps/preview-vue/src/vue/input-group-kbd.vue
<script setup lang="ts">
import SearchIcon from "@material-symbols/svg-400/rounded/search.svg?component"
import {
  InputGroup,
  InputGroupAddon,
  InputGroupInput,
} from '@/ui/input-group'
import { Kbd } from '@/ui/kbd'
</script>

<template>
  <div class="flex w-full max-w-xs flex-col gap-6">
    <InputGroup>
      <InputGroupInput placeholder="Search..." />
      <InputGroupAddon>
        <SearchIcon />
      </InputGroupAddon>
      <InputGroupAddon align="inline-end">
        <Kbd>⌘</Kbd>
        <Kbd>K</Kbd>
      </InputGroupAddon>
    </InputGroup>
  </div>
</template>
