// apps/v4/examples/base/input-required.tsx
import { Field, FieldDescription, FieldLabel } from "@/examples/base/ui/field"
import { Input } from "@/examples/base/ui/input"

export function InputRequired() {
  return (
    <Field>
      <FieldLabel htmlFor="input-required">
        Required Field <span className="text-destructive">*</span>
      </FieldLabel>
      <Input
        id="input-required"
        placeholder="This field is required"
        required
      />
      <FieldDescription>This field must be filled out.</FieldDescription>
    </Field>
  )
}

// apps/preview-vue/src/vue/input-required.vue
<script setup lang="ts">
import {
  Field,
  FieldDescription,
  FieldLabel,
} from '@/ui/field'
import { Input } from '@/ui/input'
</script>

<template>
  <Field>
    <FieldLabel for="input-required">
      Required Field <span class="text-destructive">*</span>
    </FieldLabel>
    <Input
      id="input-required"
      placeholder="This field is required"
      required
    />
    <FieldDescription>This field must be filled out.</FieldDescription>
  </Field>
</template>
