// apps/v4/examples/radix/input-group-kbd.tsx
import { SearchIcon } from "@/examples/material-symbols"

import {
  InputGroup,
  InputGroupAddon,
  InputGroupInput,
} from "@/styles/radix-force-ui/ui/input-group"
import { Kbd } from "@/styles/radix-force-ui/ui/kbd"

export function InputGroupKbd() {
  return (
    <InputGroup className="max-w-sm">
      <InputGroupInput placeholder="Search..." />
      <InputGroupAddon>
        <SearchIcon className="text-muted-foreground" />
      </InputGroupAddon>
      <InputGroupAddon align="inline-end">
        <Kbd>⌘K</Kbd>
      </InputGroupAddon>
    </InputGroup>
  )
}

// apps/preview-vue/src/vue/input-group-kbd.vue
<script setup lang="ts">
import SearchIcon from "@material-symbols/svg-400/rounded/search.svg?component"
import {
  InputGroup,
  InputGroupAddon,
  InputGroupInput,
} from '@/ui/input-group'
import { Kbd } from '@/ui/kbd'
</script>

<template>
  <div class="flex w-full max-w-xs flex-col gap-6">
    <InputGroup>
      <InputGroupInput placeholder="Search..." />
      <InputGroupAddon>
        <SearchIcon />
      </InputGroupAddon>
      <InputGroupAddon align="inline-end">
        <Kbd>⌘</Kbd>
        <Kbd>K</Kbd>
      </InputGroupAddon>
    </InputGroup>
  </div>
</template>
