// apps/preview-svelte/src/svelte/item-rtl.svelte
<script lang="ts">
	import * as Item from "@/svelte-ui/item/index.js";
	import { Button } from "@/svelte-ui/button/index.js";
	import BadgeCheckIcon from "~icons/ms/verified";
	import ChevronRightIcon from "~icons/ms/chevron_right";
</script>

<div class="flex w-full max-w-md flex-col gap-6" dir="rtl">
	<Item.Root variant="outline" dir="rtl">
		<Item.Content>
			<Item.Title>عنصر أساسي</Item.Title>
			<Item.Description>عنصر بسيط يحتوي على عنوان ووصف.</Item.Description>
		</Item.Content>
		<Item.Actions>
			<Button variant="outline" size="sm">إجراء</Button>
		</Item.Actions>
	</Item.Root>
	<Item.Root variant="outline" size="sm" dir="rtl">
		{#snippet child({ props })}
			<a href="#/" {...props}>
				<Item.Media>
					<BadgeCheckIcon class="size-5" />
				</Item.Media>
				<Item.Content>
					<Item.Title>تم التحقق من ملفك الشخصي.</Item.Title>
				</Item.Content>
				<Item.Actions>
					<ChevronRightIcon class="size-4" />
				</Item.Actions>
			</a>
		{/snippet}
	</Item.Root>
</div>

// apps/preview-vue/src/vue/item-rtl.vue
<script setup lang="ts">
import BadgeCheckIcon from "@material-symbols/svg-400/rounded/verified.svg?component"
import ChevronRightIcon from "@material-symbols/svg-400/rounded/chevron_right.svg?component"
import { Button } from '@/ui/button'
import {
  Item,
  ItemActions,
  ItemContent,
  ItemDescription,
  ItemMedia,
  ItemTitle,
} from '@/ui/item'
</script>

<template>
  <div class="flex w-full max-w-md flex-col gap-6" dir="rtl">
    <Item variant="outline" dir="rtl">
      <ItemContent>
        <ItemTitle>عنصر أساسي</ItemTitle>
        <ItemDescription>
          عنصر بسيط يحتوي على عنوان ووصف.
        </ItemDescription>
      </ItemContent>
      <ItemActions>
        <Button variant="outline" size="sm">
          إجراء
        </Button>
      </ItemActions>
    </Item>
    <Item variant="outline" size="sm" as-child dir="rtl">
      <a href="#">
        <ItemMedia>
          <BadgeCheckIcon class="size-5" />
        </ItemMedia>
        <ItemContent>
          <ItemTitle>تم التحقق من ملفك الشخصي.</ItemTitle>
        </ItemContent>
        <ItemActions>
          <ChevronRightIcon class="size-4" />
        </ItemActions>
      </a>
    </Item>
  </div>
</template>
