// apps/v4/examples/react-aria/popover-form.tsx
import { Button } from "@/examples/react-aria/ui/button"
import { Field, FieldGroup, FieldLabel } from "@/examples/react-aria/ui/field"
import { Input } from "@/examples/react-aria/ui/input"
import {
  Popover,
  PopoverContent,
  PopoverDescription,
  PopoverHeader,
  PopoverTitle,
  PopoverTrigger,
} from "@/examples/react-aria/ui/popover"

export function PopoverForm() {
  return (
    <>
      <Popover>
        <PopoverTrigger render={<Button variant="outline" />}>
          Open Popover
        </PopoverTrigger>
        <PopoverContent className="w-64" align="start">
          <PopoverHeader>
            <PopoverTitle>Dimensions</PopoverTitle>
            <PopoverDescription>
              Set the dimensions for the layer.
            </PopoverDescription>
          </PopoverHeader>
          <FieldGroup className="gap-4">
            <Field orientation="horizontal">
              <FieldLabel htmlFor="width" className="w-1/2">
                Width
              </FieldLabel>
              <Input id="width" defaultValue="100%" />
            </Field>
            <Field orientation="horizontal">
              <FieldLabel htmlFor="height" className="w-1/2">
                Height
              </FieldLabel>
              <Input id="height" defaultValue="25px" />
            </Field>
          </FieldGroup>
        </PopoverContent>
      </Popover>
    </>
  )
}

// apps/preview-vue/src/vue/popover-form.vue
<script setup lang="ts">
import { Button } from '@/ui/button'
import {
  Field,
  FieldGroup,
  FieldLabel,
} from '@/ui/field'
import { Input } from '@/ui/input'
import {
  Popover,
  PopoverContent,
  PopoverDescription,
  PopoverHeader,
  PopoverTitle,
  PopoverTrigger,
} from '@/ui/popover'
</script>

<template>
  <Popover>
    <PopoverTrigger as-child>
      <Button variant="outline">Open Popover</Button>
    </PopoverTrigger>
    <PopoverContent class="w-64" align="start">
      <PopoverHeader>
        <PopoverTitle>Dimensions</PopoverTitle>
        <PopoverDescription>
          Set the dimensions for the layer.
        </PopoverDescription>
      </PopoverHeader>
      <FieldGroup class="gap-4">
        <Field orientation="horizontal">
          <FieldLabel for="width" class="w-1/2">
            Width
          </FieldLabel>
          <Input id="width" default-value="100%" />
        </Field>
        <Field orientation="horizontal">
          <FieldLabel for="height" class="w-1/2">
            Height
          </FieldLabel>
          <Input id="height" default-value="25px" />
        </Field>
      </FieldGroup>
    </PopoverContent>
  </Popover>
</template>
