// apps/v4/examples/base/spinner-rtl.tsx
"use client"

import * as React from "react"
import {
  Item,
  ItemContent,
  ItemMedia,
  ItemTitle,
} from "@/examples/base/ui-rtl/item"
import { Spinner } from "@/examples/base/ui-rtl/spinner"

import {
  useTranslation,
  type Translations,
} from "@/components/language-selector"

const translations: Translations = {
  en: {
    dir: "ltr",
    values: {
      title: "Processing payment...",
      amount: "$100.00",
    },
  },
  ar: {
    dir: "rtl",
    values: {
      title: "جاري معالجة الدفع...",
      amount: "١٠٠.٠٠ دولار",
    },
  },
  he: {
    dir: "rtl",
    values: {
      title: "מעבד תשלום...",
      amount: "$100.00",
    },
  },
}

export function SpinnerRtl() {
  const { dir, t } = useTranslation(translations, "ar")

  return (
    <div
      className="flex w-full max-w-xs flex-col gap-4 [--radius:1rem]"
      dir={dir}
    >
      <Item variant="muted" dir={dir}>
        <ItemMedia>
          <Spinner />
        </ItemMedia>
        <ItemContent>
          <ItemTitle className="line-clamp-1">{t.title}</ItemTitle>
        </ItemContent>
        <ItemContent className="flex-none justify-end">
          <span className="text-sm tabular-nums">{t.amount}</span>
        </ItemContent>
      </Item>
    </div>
  )
}

// apps/preview-vue/src/vue/spinner-rtl.vue
<script setup lang="ts">
import {
  Item,
  ItemContent,
  ItemMedia,
  ItemTitle,
} from '@/ui/item'
import { Spinner } from '@/ui/spinner'
</script>

<template>
  <div class="flex w-full max-w-xs flex-col gap-4 [--radius:1rem]" dir="rtl">
    <Item variant="muted" dir="rtl">
      <ItemMedia>
        <Spinner />
      </ItemMedia>
      <ItemContent>
        <ItemTitle class="line-clamp-1">جاري معالجة الدفع...</ItemTitle>
      </ItemContent>
      <ItemContent class="flex-none justify-end">
        <span class="text-sm tabular-nums">١٠٠.٠٠ دولار</span>
      </ItemContent>
    </Item>
  </div>
</template>
