// apps/v4/examples/base/tooltip-keyboard.tsx
import { SaveIcon } from "@/examples/material-symbols"

import { Button } from "@/styles/base-force-ui/ui/button"
import { Kbd } from "@/styles/base-force-ui/ui/kbd"
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from "@/styles/base-force-ui/ui/tooltip"

export function TooltipKeyboard() {
  return (
    <Tooltip>
      <TooltipTrigger render={<Button variant="outline" size="icon-sm" />}>
        <SaveIcon />
      </TooltipTrigger>
      <TooltipContent>
        Save Changes <Kbd>S</Kbd>
      </TooltipContent>
    </Tooltip>
  )
}

// apps/preview-vue/src/vue/tooltip-keyboard.vue
<script setup lang="ts">
import SaveIcon from "@material-symbols/svg-400/rounded/save.svg?component"
import { Button } from '@/ui/button'
import { Kbd } from '@/ui/kbd'
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from '@/ui/tooltip'
</script>

<template>
  <TooltipProvider>
    <Tooltip>
      <TooltipTrigger as-child>
        <Button variant="outline" size="icon-sm">
          <SaveIcon />
        </Button>
      </TooltipTrigger>
      <TooltipContent>
        Save Changes <Kbd>S</Kbd>
      </TooltipContent>
    </Tooltip>
  </TooltipProvider>
</template>
