// apps/v4/examples/radix/button-group-basic.tsx
import { Button } from "@/examples/radix/ui/button"
import { ButtonGroup } from "@/examples/radix/ui/button-group"

export function ButtonGroupBasic() {
  return (
    <div className="flex flex-col gap-4">
      <ButtonGroup>
        <Button variant="outline">Button</Button>
        <Button variant="outline">Another Button</Button>
      </ButtonGroup>
    </div>
  )
}

// apps/v4/preview-server/src/vue/ButtonGroupBasic.vue
<script setup lang="ts">
import { Button } from "@/ui/button"
import { ButtonGroup } from "@/ui/button-group"
import { Example } from "@/components"
</script>

<template>
  <Example title="Basic">
    <div class="flex flex-col gap-4">
      <ButtonGroup>
        <Button variant="outline">
          Button
        </Button>
        <Button variant="outline">
          Another Button
        </Button>
      </ButtonGroup>
    </div>
  </Example>
</template>
