// apps/v4/examples/radix/button-group-with-input.tsx
import { Button } from "@/examples/radix/ui/button"
import { ButtonGroup } from "@/examples/radix/ui/button-group"
import { Input } from "@/examples/radix/ui/input"

export function ButtonGroupWithInput() {
  return (
    <div className="flex flex-col gap-4">
      <ButtonGroup>
        <Button variant="outline">Button</Button>
        <Input placeholder="Type something here..." />
      </ButtonGroup>
      <ButtonGroup>
        <Input placeholder="Type something here..." />
        <Button variant="outline">Button</Button>
      </ButtonGroup>
    </div>
  )
}

// apps/v4/preview-server/src/vue/ButtonGroupWithInput.vue
<script setup lang="ts">
import { Button } from "@/ui/button"
import { ButtonGroup } from "@/ui/button-group"
import { Input } from "@/ui/input"
import { Example } from "@/components"
</script>

<template>
  <Example title="With Input">
    <div class="flex flex-col gap-4">
      <ButtonGroup>
        <Button variant="outline">
          Button
        </Button>
        <Input placeholder="Type something here..." />
      </ButtonGroup>
      <ButtonGroup>
        <Input placeholder="Type something here..." />
        <Button variant="outline">
          Button
        </Button>
      </ButtonGroup>
    </div>
  </Example>
</template>
