// apps/v4/examples/base/calendar-booked-dates.tsx
"use client"

import * as React from "react"
import { Calendar } from "@/examples/base/ui/calendar"
import { Card, CardContent } from "@/examples/base/ui/card"

export function CalendarBookedDates() {
  const [date, setDate] = React.useState<Date | undefined>(
    new Date(new Date().getFullYear(), 0, 6)
  )
  const bookedDates = Array.from(
    { length: 15 },
    (_, i) => new Date(new Date().getFullYear(), 0, 12 + i)
  )

  return (
    <Card className="mx-auto w-fit p-0">
      <CardContent className="p-0">
        <Calendar
          mode="single"
          defaultMonth={date}
          selected={date}
          onSelect={setDate}
          disabled={bookedDates}
          modifiers={{
            booked: bookedDates,
          }}
          modifiersClassNames={{
            booked: "[&>button]:line-through opacity-100",
          }}
        />
      </CardContent>
    </Card>
  )
}

// apps/v4/preview-server/src/vue/CalendarBookedDates.vue
<script setup lang="ts">
import { CalendarDate } from "@internationalized/date"
import { ref } from "vue"
import { Calendar } from "@/ui/calendar"
import { Card, CardContent } from "@/ui/card"
import { Example } from "@/components"

const date = ref<CalendarDate>(
  new CalendarDate(
    new Date().getFullYear(),
    2,
    3,
  ),
)

const bookedDates = Array.from(
  { length: 15 },
  (_, i) => new CalendarDate(
    new Date().getFullYear(),
    2,
    12 + i,
  ),
)
</script>

<template>
  <Example title="Booked Dates">
    <Card class="mx-auto w-fit p-0">
      <CardContent class="p-0">
        <Calendar
          v-model="date"
          :disabled="bookedDates"
          :is-date-unavailable="(date) => bookedDates.some(d => d.compare(date) === 0)"
        />
      </CardContent>
    </Card>
  </Example>
</template>
