// apps/v4/examples/radix/calendar-multiple.tsx
import { Calendar } from "@/examples/radix/ui/calendar"
import { Card, CardContent } from "@/examples/radix/ui/card"

export function CalendarMultiple() {
  return (
    <Card className="mx-auto w-fit p-0">
      <CardContent className="p-0">
        <Calendar mode="multiple" />
      </CardContent>
    </Card>
  )
}

// apps/v4/preview-server/src/vue/CalendarMultiple.vue
<script setup lang="ts">
import { Calendar } from "@/ui/calendar"
import { Card, CardContent } from "@/ui/card"
import { Example } from "@/components"
</script>

<template>
  <Example title="Multiple">
    <Card class="mx-auto w-fit p-0">
      <CardContent class="p-0">
        <Calendar type="multiple" />
      </CardContent>
    </Card>
  </Example>
</template>
