// apps/v4/examples/radix/card-footer-with-border.tsx
import { Button } from "@/examples/radix/ui/button"
import { Card, CardContent, CardFooter } from "@/examples/radix/ui/card"

export function CardFooterWithBorder() {
  return (
    <Card className="mx-auto w-full max-w-sm">
      <CardContent>
        <p>
          The footer has a border-t class applied, creating a visual separation
          between the content and footer sections.
        </p>
      </CardContent>
      <CardFooter className="border-t">
        <Button variant="outline" className="w-full">
          Footer with Border
        </Button>
      </CardFooter>
    </Card>
  )
}

// apps/v4/preview-server/src/vue/CardFooterWithBorder.vue
<script setup lang="ts">
import { Button } from "@/ui/button"
import {
  Card,
  CardContent,
  CardFooter,
} from "@/ui/card"
import { Example } from "@/components"
</script>

<template>
  <Example title="Footer with Border">
    <Card class="mx-auto w-full max-w-sm">
      <CardContent>
        <p>
          The footer has a border-t class applied, creating a visual
          separation between the content and footer sections.
        </p>
      </CardContent>
      <CardFooter class="border-t">
        <Button variant="outline" class="w-full">
          Footer with Border
        </Button>
      </CardFooter>
    </Card>
  </Example>
</template>
