// apps/v4/examples/base/combobox-large-list.tsx
import {
  Combobox,
  ComboboxContent,
  ComboboxEmpty,
  ComboboxInput,
  ComboboxItem,
  ComboboxList,
} from "@/examples/base/ui/combobox"
import { Item } from "@/examples/base/ui/item"
import { Select } from "@/examples/base/ui/select"

const largeListItems = Array.from({ length: 100 }, (_, i) => `Item ${i + 1}`)

const items = [
  {
    label: "Select a framework",
    value: null,
  },
  {
    label: "React",
    value: "react",
  },
  {
    label: "Vue",
    value: "vue",
  },
  {
    label: "Angular",
    value: "angular",
  },
  {
    label: "Svelte",
    value: "svelte",
  },
  {
    label: "Solid",
    value: "solid",
  },
  {
    label: "Preact",
    value: "preact",
  },
  {
    label: "Next.js",
    value: "next.js",
  },
]

export function ComboboxLargeList() {
  return (
    <Combobox items={largeListItems}>
      <ComboboxInput placeholder="Search from 100 items" />
      <ComboboxContent>
        <ComboboxEmpty>No items found.</ComboboxEmpty>
        <ComboboxList>
          {(item) => (
            <ComboboxItem key={item} value={item}>
              {item}
            </ComboboxItem>
          )}
        </ComboboxList>
      </ComboboxContent>
    </Combobox>
  )
}

// apps/v4/preview-server/src/vue/ComboboxLargeList.vue
<script setup lang="ts">
import { Example } from "@/components"
import {
  Combobox,
  ComboboxEmpty,
  ComboboxInput,
  ComboboxItem,
  ComboboxList,
  ComboboxViewport,
} from "@/ui/combobox"

const largeListItems = Array.from({ length: 100 }, (_, i) => `Item ${i + 1}`)
</script>

<template>
  <Example title="Large List (100 items)">
    <Combobox :items="largeListItems">
      <ComboboxInput placeholder="Search from 100 items" />
      <ComboboxList>
        <ComboboxViewport>
          <ComboboxEmpty>No items found.</ComboboxEmpty>
          <ComboboxItem
            v-for="item in largeListItems"
            :key="item"
            :value="item"
          >
            {{ item }}
          </ComboboxItem>
        </ComboboxViewport>
      </ComboboxList>
    </Combobox>
  </Example>
</template>
