// apps/v4/examples/radix/input-with-native-select.tsx
import { Input } from "@/examples/radix/ui/input"
import {
  NativeSelect,
  NativeSelectOption,
} from "@/examples/radix/ui/native-select"
import { Select } from "@/examples/radix/ui/select"

export function InputWithNativeSelect() {
  return (
    <div className="flex w-full gap-2">
      <Input type="tel" placeholder="(555) 123-4567" className="flex-1" />
      <NativeSelect defaultValue="+1">
        <NativeSelectOption value="+1">+1</NativeSelectOption>
        <NativeSelectOption value="+44">+44</NativeSelectOption>
        <NativeSelectOption value="+46">+46</NativeSelectOption>
      </NativeSelect>
    </div>
  )
}

// apps/v4/preview-server/src/vue/InputWithNativeSelect.vue
<script setup lang="ts">
import { Input } from "@/ui/input"
import { NativeSelect, NativeSelectOption } from "@/ui/native-select"
</script>

<template>
  <div class="flex w-full gap-2">
    <Input type="tel" placeholder="(555) 123-4567" class="flex-1" />
    <NativeSelect default-value="+1">
      <NativeSelectOption value="+1">
        +1
      </NativeSelectOption>
      <NativeSelectOption value="+44">
        +44
      </NativeSelectOption>
      <NativeSelectOption value="+46">
        +46
      </NativeSelectOption>
    </NativeSelect>
  </div>
</template>
