// apps/v4/examples/radix/label-with-input.tsx
import { Field } from "@/examples/radix/ui/field"
import { Input } from "@/examples/radix/ui/input"
import { Label } from "@/examples/radix/ui/label"

export function LabelWithInput() {
  return (
    <Field>
      <Label htmlFor="label-demo-username">Username</Label>
      <Input id="label-demo-username" placeholder="Username" />
    </Field>
  )
}

// apps/v4/preview-server/src/vue/LabelWithInput.vue
<script setup lang="ts">
import { Example } from "@/components"
import { Field } from "@/ui/field"
import { Input } from "@/ui/input"
import { Label } from "@/ui/label"
</script>

<template>
  <Example title="With Input">
    <Field>
      <Label html-for="label-demo-username">Username</Label>
      <Input id="label-demo-username" placeholder="Username" />
    </Field>
  </Example>
</template>
