// apps/v4/examples/base/select-fields.tsx
import {
  Field,
  FieldDescription,
  FieldGroup,
  FieldLabel,
} from "@/examples/base/ui/field"
import {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/examples/base/ui/select"

export function SelectFields() {
  const basicItems = [
    { label: "Choose an option", value: null },
    { label: "Option 1", value: "option1" },
    { label: "Option 2", value: "option2" },
    { label: "Option 3", value: "option3" },
  ]
  const countryItems = [
    { label: "Select your country", value: null },
    { label: "United States", value: "us" },
    { label: "United Kingdom", value: "uk" },
    { label: "Canada", value: "ca" },
  ]
  const timezoneItems = [
    { label: "Select timezone", value: null },
    { label: "UTC", value: "utc" },
    { label: "Eastern Time", value: "est" },
    { label: "Pacific Time", value: "pst" },
  ]
  const invalidItems = [
    { label: "This field has an error", value: null },
    { label: "Option 1", value: "option1" },
    { label: "Option 2", value: "option2" },
    { label: "Option 3", value: "option3" },
  ]
  const disabledItems = [
    { label: "Cannot select", value: null },
    { label: "Option 1", value: "option1" },
    { label: "Option 2", value: "option2" },
    { label: "Option 3", value: "option3" },
  ]

  return (
    <FieldGroup>
      <Field>
        <FieldLabel htmlFor="select-basic">Basic Select</FieldLabel>
        <Select items={basicItems}>
          <SelectTrigger id="select-basic">
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            <SelectGroup>
              {basicItems.map((item) => (
                <SelectItem key={item.value} value={item.value}>
                  {item.label}
                </SelectItem>
              ))}
            </SelectGroup>
          </SelectContent>
        </Select>
      </Field>
      <Field>
        <FieldLabel htmlFor="select-country">Country</FieldLabel>
        <Select items={countryItems}>
          <SelectTrigger id="select-country">
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            <SelectGroup>
              {countryItems.map((item) => (
                <SelectItem key={item.value} value={item.value}>
                  {item.label}
                </SelectItem>
              ))}
            </SelectGroup>
          </SelectContent>
        </Select>
        <FieldDescription>
          Select the country where you currently reside.
        </FieldDescription>
      </Field>
      <Field>
        <FieldLabel htmlFor="select-timezone">Timezone</FieldLabel>
        <FieldDescription>
          Choose your local timezone for accurate scheduling.
        </FieldDescription>
        <Select items={timezoneItems}>
          <SelectTrigger id="select-timezone">
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            <SelectGroup>
              {timezoneItems.map((item) => (
                <SelectItem key={item.value} value={item.value}>
                  {item.label}
                </SelectItem>
              ))}
            </SelectGroup>
          </SelectContent>
        </Select>
      </Field>
      <Field data-invalid>
        <FieldLabel htmlFor="select-invalid">Invalid Select</FieldLabel>
        <Select items={invalidItems}>
          <SelectTrigger id="select-invalid" aria-invalid>
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            <SelectGroup>
              {invalidItems.map((item) => (
                <SelectItem key={item.value} value={item.value}>
                  {item.label}
                </SelectItem>
              ))}
            </SelectGroup>
          </SelectContent>
        </Select>
        <FieldDescription>
          This field contains validation errors.
        </FieldDescription>
      </Field>
      <Field data-disabled>
        <FieldLabel htmlFor="select-disabled-field">Disabled Field</FieldLabel>
        <Select items={disabledItems} disabled>
          <SelectTrigger id="select-disabled-field">
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            <SelectGroup>
              {disabledItems.map((item) => (
                <SelectItem key={item.value} value={item.value}>
                  {item.label}
                </SelectItem>
              ))}
            </SelectGroup>
          </SelectContent>
        </Select>
        <FieldDescription>This field is currently disabled.</FieldDescription>
      </Field>
    </FieldGroup>
  )
}

// apps/v4/preview-server/src/vue/SelectFields.vue
<script setup lang="ts">
import { Example } from "@/components"
import {
  Field,
  FieldDescription,
  FieldGroup,
  FieldLabel,
} from "@/ui/field"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/ui/select"
</script>

<template>
  <Example title="Select Fields">
    <FieldGroup>
      <Field>
        <FieldLabel html-for="select-basic">
          Basic Select
        </FieldLabel>
        <Select>
          <SelectTrigger id="select-basic">
            <SelectValue placeholder="Choose an option" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="option1">
              Option 1
            </SelectItem>
            <SelectItem value="option2">
              Option 2
            </SelectItem>
            <SelectItem value="option3">
              Option 3
            </SelectItem>
          </SelectContent>
        </Select>
      </Field>
      <Field>
        <FieldLabel html-for="select-country">
          Country
        </FieldLabel>
        <Select>
          <SelectTrigger id="select-country">
            <SelectValue placeholder="Select your country" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="us">
              United States
            </SelectItem>
            <SelectItem value="uk">
              United Kingdom
            </SelectItem>
            <SelectItem value="ca">
              Canada
            </SelectItem>
          </SelectContent>
        </Select>
        <FieldDescription>
          Select the country where you currently reside.
        </FieldDescription>
      </Field>
      <Field>
        <FieldLabel html-for="select-timezone">
          Timezone
        </FieldLabel>
        <FieldDescription>
          Choose your local timezone for accurate scheduling.
        </FieldDescription>
        <Select>
          <SelectTrigger id="select-timezone">
            <SelectValue placeholder="Select timezone" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="utc">
              UTC
            </SelectItem>
            <SelectItem value="est">
              Eastern Time
            </SelectItem>
            <SelectItem value="pst">
              Pacific Time
            </SelectItem>
          </SelectContent>
        </Select>
      </Field>
      <Field data-invalid>
        <FieldLabel html-for="select-invalid">
          Invalid Select
        </FieldLabel>
        <Select>
          <SelectTrigger id="select-invalid" :aria-invalid="true">
            <SelectValue placeholder="This field has an error" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="option1">
              Option 1
            </SelectItem>
            <SelectItem value="option2">
              Option 2
            </SelectItem>
            <SelectItem value="option3">
              Option 3
            </SelectItem>
          </SelectContent>
        </Select>
        <FieldDescription>
          This field contains validation errors.
        </FieldDescription>
      </Field>
      <Field data-disabled>
        <FieldLabel html-for="select-disabled-field">
          Disabled Field
        </FieldLabel>
        <Select :disabled="true">
          <SelectTrigger id="select-disabled-field">
            <SelectValue placeholder="Cannot select" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="option1">
              Option 1
            </SelectItem>
            <SelectItem value="option2">
              Option 2
            </SelectItem>
            <SelectItem value="option3">
              Option 3
            </SelectItem>
          </SelectContent>
        </Select>
        <FieldDescription>This field is currently disabled.</FieldDescription>
      </Field>
    </FieldGroup>
  </Example>
</template>
