// apps/v4/examples/base/spinner-in-input-group.tsx
import { Field, FieldLabel } from "@/examples/base/ui/field"
import {
  InputGroup,
  InputGroupAddon,
  InputGroupInput,
} from "@/examples/base/ui/input-group"
import { Spinner } from "@/examples/base/ui/spinner"

export function SpinnerInInputGroup() {
  return (
    <Field>
      <FieldLabel htmlFor="input-group-spinner">Input Group</FieldLabel>
      <InputGroup>
        <InputGroupInput id="input-group-spinner" />
        <InputGroupAddon>
          <Spinner />
        </InputGroupAddon>
      </InputGroup>
    </Field>
  )
}

// apps/v4/preview-server/src/vue/SpinnerInInputGroup.vue
<script setup lang="ts">
import { Example } from "@/components"
import { Field, FieldLabel } from "@/ui/field"
import {
  InputGroup,
  InputGroupAddon,
  InputGroupInput,
} from "@/ui/input-group"
import { Spinner } from "@/ui/spinner"
</script>

<template>
  <Example title="In Input Group">
    <Field>
      <FieldLabel html-for="input-group-spinner">
        Input Group
      </FieldLabel>
      <InputGroup>
        <InputGroupInput id="input-group-spinner" />
        <InputGroupAddon>
          <Spinner />
        </InputGroupAddon>
      </InputGroup>
    </Field>
  </Example>
</template>
