// apps/v4/examples/radix/tabs-variants-comparison.tsx
import { Tabs, TabsList, TabsTrigger } from "@/examples/radix/ui/tabs"

export function TabsVariantsComparison() {
  return (
    <div className="flex gap-4">
      <Tabs defaultValue="overview">
        <TabsList>
          <TabsTrigger value="overview">Overview</TabsTrigger>
          <TabsTrigger value="analytics">Analytics</TabsTrigger>
        </TabsList>
      </Tabs>
      <Tabs defaultValue="overview">
        <TabsList variant="line">
          <TabsTrigger value="overview">Overview</TabsTrigger>
          <TabsTrigger value="analytics">Analytics</TabsTrigger>
        </TabsList>
      </Tabs>
    </div>
  )
}

// apps/v4/preview-server/src/vue/TabsVariantsComparison.vue
<script setup lang="ts">
import { Tabs, TabsList, TabsTrigger } from "@/ui/tabs"
</script>

<template>
  <div class="flex gap-4">
    <Tabs default-value="overview">
      <TabsList>
        <TabsTrigger value="overview">
          Overview
        </TabsTrigger>
        <TabsTrigger value="analytics">
          Analytics
        </TabsTrigger>
      </TabsList>
    </Tabs>
    <Tabs default-value="overview">
      <TabsList variant="line">
        <TabsTrigger value="overview">
          Overview
        </TabsTrigger>
        <TabsTrigger value="analytics">
          Analytics
        </TabsTrigger>
      </TabsList>
    </Tabs>
  </div>
</template>
