// apps/v4/examples/base/tooltip-on-link.tsx
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from "@/examples/base/ui/tooltip"

export function TooltipOnLink() {
  return (
    <Tooltip>
      <TooltipTrigger
        render={
          <a
            href="#"
            className="text-primary w-fit text-sm underline-offset-4 hover:underline"
            onClick={(e) => e.preventDefault()}
          />
        }
      >
        Learn more
      </TooltipTrigger>
      <TooltipContent>
        <p>Click to read the documentation</p>
      </TooltipContent>
    </Tooltip>
  )
}

// apps/v4/preview-server/src/vue/TooltipOnLink.vue
<script setup lang="ts">
import { Example } from "@/components"
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from "@/ui/tooltip"
</script>

<template>
  <Example title="On Link">
    <Tooltip>
      <TooltipTrigger :as-child="true">
        <a
          href="#"
          class="w-fit text-sm text-primary underline-offset-4 hover:underline"
          @click.prevent
        >
          Learn more
        </a>
      </TooltipTrigger>
      <TooltipContent>
        <p>Click to read the documentation</p>
      </TooltipContent>
    </Tooltip>
  </Example>
</template>
