// apps/v4/registry/bases/vue/examples/resizable/ResizableExample.vue
<script setup lang="ts">
import { ref } from "vue"
import { Example, ExampleWrapper } from "@/components/example"
import {
  ResizableHandle,
  ResizablePanel,
  ResizablePanelGroup,
} from "@/ui/resizable"

const sizes = ref([30, 70])
</script>

<template>
  <ExampleWrapper>
    <Example title="Horizontal">
      <ResizablePanelGroup
        direction="horizontal"
        class="min-h-[200px] rounded-lg border"
      >
        <ResizablePanel :default-size="25">
          <div class="flex h-full items-center justify-center p-6">
            <span class="font-semibold">Sidebar</span>
          </div>
        </ResizablePanel>
        <ResizableHandle />
        <ResizablePanel :default-size="75">
          <div class="flex h-full items-center justify-center p-6">
            <span class="font-semibold">Content</span>
          </div>
        </ResizablePanel>
      </ResizablePanelGroup>
    </Example>

    <Example title="Vertical">
      <ResizablePanelGroup
        direction="vertical"
        class="min-h-[200px] rounded-lg border"
      >
        <ResizablePanel :default-size="25">
          <div class="flex h-full items-center justify-center p-6">
            <span class="font-semibold">Header</span>
          </div>
        </ResizablePanel>
        <ResizableHandle />
        <ResizablePanel :default-size="75">
          <div class="flex h-full items-center justify-center p-6">
            <span class="font-semibold">Content</span>
          </div>
        </ResizablePanel>
      </ResizablePanelGroup>
    </Example>

    <Example title="With Handle">
      <ResizablePanelGroup
        direction="horizontal"
        class="min-h-[200px] rounded-lg border"
      >
        <ResizablePanel :default-size="25">
          <div class="flex h-full items-center justify-center p-6">
            <span class="font-semibold">Sidebar</span>
          </div>
        </ResizablePanel>
        <ResizableHandle :with-handle="true" />
        <ResizablePanel :default-size="75">
          <div class="flex h-full items-center justify-center p-6">
            <span class="font-semibold">Content</span>
          </div>
        </ResizablePanel>
      </ResizablePanelGroup>
    </Example>

    <Example title="Nested">
      <ResizablePanelGroup direction="horizontal" class="rounded-lg border">
        <ResizablePanel :default-size="50">
          <div class="flex h-[200px] items-center justify-center p-6">
            <span class="font-semibold">One</span>
          </div>
        </ResizablePanel>
        <ResizableHandle />
        <ResizablePanel :default-size="50">
          <ResizablePanelGroup direction="vertical">
            <ResizablePanel :default-size="25">
              <div class="flex h-full items-center justify-center p-6">
                <span class="font-semibold">Two</span>
              </div>
            </ResizablePanel>
            <ResizableHandle />
            <ResizablePanel :default-size="75">
              <div class="flex h-full items-center justify-center p-6">
                <span class="font-semibold">Three</span>
              </div>
            </ResizablePanel>
          </ResizablePanelGroup>
        </ResizablePanel>
      </ResizablePanelGroup>
    </Example>

    <Example title="Controlled">
      <ResizablePanelGroup
        direction="horizontal"
        class="min-h-[200px] rounded-lg border"
        @layout="(newSizes) => { sizes = newSizes }"
      >
        <ResizablePanel :default-size="30" :min-size="20">
          <div class="flex h-full flex-col items-center justify-center gap-2 p-6">
            <span class="font-semibold">{{ Math.round(sizes[0] ?? 30) }}%</span>
          </div>
        </ResizablePanel>
        <ResizableHandle />
        <ResizablePanel :default-size="70" :min-size="30">
          <div class="flex h-full flex-col items-center justify-center gap-2 p-6">
            <span class="font-semibold">{{ Math.round(sizes[1] ?? 70) }}%</span>
          </div>
        </ResizablePanel>
      </ResizablePanelGroup>
    </Example>
  </ExampleWrapper>
</template>

// apps/v4/registry/ark-lyra/examples/resizable-example.tsx
"use client"

import * as React from "react"

import {
  Example,
  ExampleWrapper,
} from "@/registry/ark-lyra/components/example"
import {
  ResizableHandle,
  ResizablePanel,
  ResizablePanelGroup,
} from "@/registry/ark-lyra/ui/resizable"

export default function ResizableExample() {
  return (
    <ExampleWrapper>
      <ResizableHorizontal />
      <ResizableVertical />
      <ResizableWithHandle />
      <ResizableNested />
      <ResizableControlled />
    </ExampleWrapper>
  )
}

function ResizableHorizontal() {
  return (
    <Example title="Horizontal">
      <ResizablePanelGroup
        panels={[{ id: "a" }, { id: "b" }]}
        className="min-h-[200px] rounded-lg border"
      >
        <ResizablePanel id="a">
          <div className="flex h-full items-center justify-center p-6">
            <span className="font-semibold">Sidebar</span>
          </div>
        </ResizablePanel>
        <ResizableHandle id="a:b" />
        <ResizablePanel id="b">
          <div className="flex h-full items-center justify-center p-6">
            <span className="font-semibold">Content</span>
          </div>
        </ResizablePanel>
      </ResizablePanelGroup>
    </Example>
  )
}

function ResizableVertical() {
  return (
    <Example title="Vertical">
      <ResizablePanelGroup
        panels={[{ id: "a" }, { id: "b" }]}
        orientation="vertical"
        className="min-h-[200px] rounded-lg border"
      >
        <ResizablePanel id="a">
          <div className="flex h-full items-center justify-center p-6">
            <span className="font-semibold">Header</span>
          </div>
        </ResizablePanel>
        <ResizableHandle id="a:b" />
        <ResizablePanel id="b">
          <div className="flex h-full items-center justify-center p-6">
            <span className="font-semibold">Content</span>
          </div>
        </ResizablePanel>
      </ResizablePanelGroup>
    </Example>
  )
}

function ResizableWithHandle() {
  return (
    <Example title="With Handle">
      <ResizablePanelGroup
        panels={[{ id: "a" }, { id: "b" }]}
        className="min-h-[200px] rounded-lg border"
      >
        <ResizablePanel id="a">
          <div className="flex h-full items-center justify-center p-6">
            <span className="font-semibold">Sidebar</span>
          </div>
        </ResizablePanel>
        <ResizableHandle id="a:b" withHandle />
        <ResizablePanel id="b">
          <div className="flex h-full items-center justify-center p-6">
            <span className="font-semibold">Content</span>
          </div>
        </ResizablePanel>
      </ResizablePanelGroup>
    </Example>
  )
}

function ResizableNested() {
  return (
    <Example title="Nested">
      <ResizablePanelGroup
        panels={[{ id: "a" }, { id: "b" }]}
        className="rounded-lg border"
      >
        <ResizablePanel id="a">
          <div className="flex h-[200px] items-center justify-center p-6">
            <span className="font-semibold">One</span>
          </div>
        </ResizablePanel>
        <ResizableHandle id="a:b" />
        <ResizablePanel id="b">
          <ResizablePanelGroup
            panels={[{ id: "c" }, { id: "d" }]}
            orientation="vertical"
          >
            <ResizablePanel id="c">
              <div className="flex h-full items-center justify-center p-6">
                <span className="font-semibold">Two</span>
              </div>
            </ResizablePanel>
            <ResizableHandle id="c:d" />
            <ResizablePanel id="d">
              <div className="flex h-full items-center justify-center p-6">
                <span className="font-semibold">Three</span>
              </div>
            </ResizablePanel>
          </ResizablePanelGroup>
        </ResizablePanel>
      </ResizablePanelGroup>
    </Example>
  )
}

function ResizableControlled() {
  const [sizes, setSizes] = React.useState<number[]>([30, 70])

  return (
    <Example title="Controlled">
      <ResizablePanelGroup
        panels={[{ id: "left", minSize: 20 }, { id: "right", minSize: 30 }]}
        defaultSize={[30, 70]}
        className="min-h-[200px] rounded-lg border"
        onResize={(details) => setSizes(details.size)}
      >
        <ResizablePanel id="left">
          <div className="flex h-full flex-col items-center justify-center gap-2 p-6">
            <span className="font-semibold">
              {Math.round(sizes[0])}%
            </span>
          </div>
        </ResizablePanel>
        <ResizableHandle id="left:right" />
        <ResizablePanel id="right">
          <div className="flex h-full flex-col items-center justify-center gap-2 p-6">
            <span className="font-semibold">
              {Math.round(sizes[1])}%
            </span>
          </div>
        </ResizablePanel>
      </ResizablePanelGroup>
    </Example>
  )
}
