// apps/preview-svelte/src/svelte/input-inline.svelte
<script lang="ts">
	import { Button } from "@/svelte-ui/button/index.js";
	import * as Field from "@/svelte-ui/field/index.js";
	import { Input } from "@/svelte-ui/input/index.js";
</script>

<Field.Field orientation="horizontal">
	<Input type="search" placeholder="Search..." />
	<Button>Search</Button>
</Field.Field>

// shadcn/apps/v4/examples/base/input-inline.tsx
import { Button } from "@/examples/base/ui/button"
import { Field } from "@/examples/base/ui/field"
import { Input } from "@/examples/base/ui/input"

export function InputInline() {
  return (
    <Field orientation="horizontal">
      <Input type="search" placeholder="Search..." />
      <Button>Search</Button>
    </Field>
  )
}
