// apps/v4/examples/ark/input-disabled.tsx
import { Field, FieldDescription, FieldLabel } from "@/examples/ark/ui/field"
import { Input } from "@/examples/ark/ui/input"

export function InputDisabled() {
  return (
    <Field data-disabled>
      <FieldLabel htmlFor="input-demo-disabled">Email</FieldLabel>
      <Input
        id="input-demo-disabled"
        type="email"
        placeholder="Email"
        disabled
      />
      <FieldDescription>This field is currently disabled.</FieldDescription>
    </Field>
  )
}

// apps/v4/registry/bases/vue/examples/input/InputDisabled.vue
<script setup lang="ts">
import { Field, FieldLabel } from "@/ui/field"
import { Input } from "@/ui/input"
</script>

<template>
  <Field>
    <FieldLabel html-for="input-demo-disabled">
      Email
    </FieldLabel>
    <Input
      id="input-demo-disabled"
      type="email"
      placeholder="Email"
      :disabled="true"
    />
  </Field>
</template>
