// apps/v4/registry/bases/vue/ui/popover/PopoverHeader.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue"
import { cn } from "@/lib/utils"

const props = defineProps<{
  class?: HTMLAttributes["class"]
}>()
</script>

<template>
  <div
    data-slot="popover-header"
    :class="cn('cn-popover-header', props.class)"
  >
    <slot />
  </div>
</template>

// apps/v4/styles/svelte-mira/ui/popover/popover-header.svelte
<script lang="ts">
  import { cn, type WithElementRef } from "$lib/utils.js"
  import type { HTMLAttributes } from "svelte/elements"

  let {
    ref = $bindable(null),
    class: className,
    children,
    ...restProps
  }: WithElementRef<HTMLAttributes<HTMLDivElement>> = $props()
</script>

<div
  bind:this={ref}
  data-slot="popover-header"
  class={cn("cn-popover-header", className)}
  {...restProps}
>
  {@render children?.()}
</div>
