// apps/v4/examples/base/aspect-ratio1x1.tsx
import Image from "next/image"
import { AspectRatio } from "@/examples/base/ui/aspect-ratio"

export function AspectRatio1x1() {
  return (
    <AspectRatio ratio={1 / 1} className="bg-muted rounded-lg">
      <Image
        src="https://avatar.vercel.sh/shadcn1"
        alt="Photo"
        fill
        className="h-full w-full rounded-lg object-cover grayscale dark:brightness-20"
      />
    </AspectRatio>
  )
}

// apps/v4/registry/bases/vue/examples/aspect-ratio/AspectRatio1x1.vue
<script setup lang="ts">
import { AspectRatio } from "@/ui/aspect-ratio"
import { Example } from "@/components/example"
</script>

<template>
  <Example title="1:1" class="items-start">
    <AspectRatio :ratio="1 / 1" class="bg-muted rounded-lg">
      <img
        src="https://avatar.vercel.sh/shadcn1"
        alt="Photo"
        class="h-full w-full rounded-lg object-cover grayscale dark:brightness-20"
      >
    </AspectRatio>
  </Example>
</template>
