// apps/v4/registry/bases/vue/examples/calendar/CalendarMultiple.vue
<script setup lang="ts">
import { Calendar } from "@/ui/calendar"
import { Card, CardContent } from "@/ui/card"
import { Example } from "@/components/example"
</script>

<template>
  <Example title="Multiple">
    <Card class="mx-auto w-fit p-0">
      <CardContent class="p-0">
        <Calendar type="multiple" />
      </CardContent>
    </Card>
  </Example>
</template>

// apps/v4/examples/ark/calendar-multiple.tsx
import { Calendar } from "@/examples/ark/ui/calendar"
import { Card, CardContent } from "@/examples/ark/ui/card"

export function CalendarMultiple() {
  return (
    <Card className="mx-auto w-fit p-0">
      <CardContent className="p-0">
        <Calendar selectionMode="multiple" />
      </CardContent>
    </Card>
  )
}
