// apps/preview-vue/src/vue/checkbox-basic.vue
<script setup lang="ts">
import { Checkbox } from '@/ui/checkbox'
import { Field, FieldGroup, FieldLabel } from '@/ui/field'
</script>

<template>
  <FieldGroup class="mx-auto w-56">
    <Field orientation="horizontal">
      <Checkbox id="terms-checkbox-basic" name="terms-checkbox-basic" />
      <FieldLabel for="terms-checkbox-basic">
        Accept terms and conditions
      </FieldLabel>
    </Field>
  </FieldGroup>
</template>

// apps/v4/examples/ark/checkbox-basic.tsx
import { Checkbox } from "@/examples/ark/ui/checkbox"
import { Field, FieldGroup, FieldLabel } from "@/examples/ark/ui/field"

export function CheckboxBasic() {
  return (
    <FieldGroup className="mx-auto w-56">
      <Field orientation="horizontal">
        <Checkbox id="terms-checkbox-basic" name="terms-checkbox-basic">
          Accept terms and conditions
        </Checkbox>
      </Field>
    </FieldGroup>
  )
}
