// apps/preview-vue/src/vue/input-input-group.vue
<script setup lang="ts">
import InfoIcon from "@material-symbols/svg-400/rounded/info.svg?component"
import { Field, FieldLabel } from '@/ui/field'
import {
  InputGroup,
  InputGroupAddon,
  InputGroupInput,
  InputGroupText,
} from '@/ui/input-group'
</script>

<template>
  <Field>
    <FieldLabel for="input-group-url">Website URL</FieldLabel>
    <InputGroup>
      <InputGroupInput id="input-group-url" placeholder="example.com" />
      <InputGroupAddon>
        <InputGroupText>https://</InputGroupText>
      </InputGroupAddon>
      <InputGroupAddon align="inline-end">
        <InfoIcon />
      </InputGroupAddon>
    </InputGroup>
  </Field>
</template>

// apps/v4/examples/ark/input-input-group.tsx
import { Field, FieldLabel } from "@/examples/ark/ui/field"
import {
  InputGroup,
  InputGroupAddon,
  InputGroupInput,
  InputGroupText,
} from "@/examples/ark/ui/input-group"
import { InfoIcon } from "lucide-react"

export function InputInputGroup() {
  return (
    <Field>
      <FieldLabel htmlFor="input-group-url">Website URL</FieldLabel>
      <InputGroup>
        <InputGroupInput id="input-group-url" placeholder="example.com" />
        <InputGroupAddon>
          <InputGroupText>https://</InputGroupText>
        </InputGroupAddon>
        <InputGroupAddon align="inline-end">
          <InfoIcon />
        </InputGroupAddon>
      </InputGroup>
    </Field>
  )
}
