// apps/preview-vue/src/vue/progress-label.vue
<script setup lang="ts">
import { Field, FieldLabel } from '@/ui/field'
import { Progress } from '@/ui/progress'
</script>

<template>
  <Field class="w-full max-w-sm">
    <FieldLabel for="progress-upload">
      <span>Upload progress</span>
      <span class="ml-auto">66%</span>
    </FieldLabel>
    <Progress :model-value="66" id="progress-upload" />
  </Field>
</template>

// shadcn/apps/v4/examples/radix/progress-label.tsx
import { Field, FieldLabel } from "@/examples/radix/ui/field"
import { Progress } from "@/examples/radix/ui/progress"

export function ProgressWithLabel() {
  return (
    <Field className="w-full max-w-sm">
      <FieldLabel htmlFor="progress-upload">
        <span>Upload progress</span>
        <span className="ml-auto">66%</span>
      </FieldLabel>
      <Progress value={66} id="progress-upload" />
    </Field>
  )
}
