// apps/v4/preview-server/src/svelte/item-link-demo.svelte
<script lang="ts">
	import * as Item from "@/svelte-ui/item/index.js";
	import ChevronRightIcon from "@lucide/svelte/icons/chevron-right";
	import ExternalLinkIcon from "@lucide/svelte/icons/external-link";
</script>

<div class="flex w-full max-w-md flex-col gap-4">
	<Item.Root>
		{#snippet child({ props })}
			<a href="#/" {...props}>
				<Item.Content>
					<Item.Title>Visit our documentation</Item.Title>
					<Item.Description>
						Learn how to get started with our components.
					</Item.Description>
				</Item.Content>
				<Item.Actions>
					<ChevronRightIcon class="size-4" />
				</Item.Actions>
			</a>
		{/snippet}
	</Item.Root>
	<Item.Root variant="outline">
		{#snippet child({ props })}
			<a href="#/" target="_blank" rel="noopener noreferrer" {...props}>
				<Item.Content>
					<Item.Title>External resource</Item.Title>
					<Item.Description>
						Opens in a new tab with security attributes.
					</Item.Description>
				</Item.Content>
				<Item.Actions>
					<ExternalLinkIcon class="size-4" />
				</Item.Actions>
			</a>
		{/snippet}
	</Item.Root>
</div>

// apps/v4/registry/bases/vue/examples/item/ItemLinkDemo.vue
<script setup lang="ts">
import { ChevronRightIcon, ExternalLinkIcon } from 'lucide-vue-next'

import {
  Item,
  ItemActions,
  ItemContent,
  ItemDescription,
  ItemTitle,
} from '@/ui/item'
</script>

<template>
  <div class="flex w-full max-w-md flex-col gap-4">
    <Item as-child>
      <a href="#">
        <ItemContent>
          <ItemTitle>Visit our documentation</ItemTitle>
          <ItemDescription>
            Learn how to get started with our components.
          </ItemDescription>
        </ItemContent>
        <ItemActions>
          <ChevronRightIcon class="size-4" />
        </ItemActions>
      </a>
    </Item>
    <Item variant="outline" as-child>
      <a href="#" target="_blank" rel="noopener noreferrer">
        <ItemContent>
          <ItemTitle>External resource</ItemTitle>
          <ItemDescription>
            Opens in a new tab with security attributes.
          </ItemDescription>
        </ItemContent>
        <ItemActions>
          <ExternalLinkIcon class="size-4" />
        </ItemActions>
      </a>
    </Item>
  </div>
</template>
