// apps/v4/registry/bases/svelte/examples/field-textarea-demo.svelte
<script lang="ts">
	import * as Field from "$lib/registry/ui/field/index.js";
	import { Textarea } from "$lib/registry/ui/textarea/index.js";
</script>

<div class="w-full max-w-md">
	<Field.Set>
		<Field.Group>
			<Field.Field>
				<Field.Label for="feedback">Feedback</Field.Label>
				<Textarea id="feedback" placeholder="Your feedback helps us improve..." rows={4} />
				<Field.Description>Share your thoughts about our service.</Field.Description>
			</Field.Field>
		</Field.Group>
	</Field.Set>
</div>

// apps/v4/registry/bases/vue/examples/field/FieldTextareaDemo.vue
<script setup lang="ts">
import {
  Field,
  FieldDescription,
  FieldGroup,
  FieldLabel,
  FieldSet,
} from '@/ui/field'
import { Textarea } from '@/ui/textarea'
</script>

<template>
  <div class="w-full max-w-md">
    <FieldSet>
      <FieldGroup>
        <Field>
          <FieldLabel for="feedback">
            Feedback
          </FieldLabel>
          <Textarea
            id="feedback"
            placeholder="Your feedback helps us improve..."
            :rows="4"
          />
          <FieldDescription>
            Share your thoughts about our service.
          </FieldDescription>
        </Field>
      </FieldGroup>
    </FieldSet>
  </div>
</template>
