// apps/v4/styles/vue-lyra/ui/tabs/Tabs.vue
<script setup lang="ts">
import { reactiveOmit } from "@vueuse/core"
import type { TabsRootEmits, TabsRootProps } from "reka-ui"
import { TabsRoot, useForwardPropsEmits } from "reka-ui"
import type { HTMLAttributes } from "vue"

import { cn } from "@/lib/utils"

const props = defineProps<TabsRootProps & { class?: HTMLAttributes["class"] }>()
const emits = defineEmits<TabsRootEmits>()

const delegatedProps = reactiveOmit(props, "class")
const forwarded = useForwardPropsEmits(delegatedProps, emits)
</script>

<template>
  <TabsRoot
    v-slot="slotProps"
    data-slot="tabs"
    :data-orientation="forwarded.orientation || 'horizontal'"
    v-bind="forwarded"
    :class="
      cn(
        'cn-tabs group/tabs flex data-[orientation=horizontal]:flex-col',
        props.class
      )
    "
  >
    <slot v-bind="slotProps" />
  </TabsRoot>
</template>

// apps/v4/preview-server/src/svelte-ui/tabs/tabs.svelte
<script lang="ts">
	import { Tabs as TabsPrimitive } from "bits-ui";
	import { cn } from "@/svelte-lib/utils.js";

	let {
		ref = $bindable(null),
		value = $bindable(""),
		class: className,
		...restProps
	}: TabsPrimitive.RootProps = $props();
</script>

<TabsPrimitive.Root
	bind:ref
	bind:value
	data-slot="tabs"
	class={cn("cn-tabs group/tabs flex data-[orientation=horizontal]:flex-col", className)}
	{...restProps}
/>
