// apps/v4/examples/base/button-group-with-input-group.tsx
import { Input } from "@/examples/base/ui/input"
import {
  InputGroup,
  InputGroupAddon,
  InputGroupInput,
} from "@/examples/base/ui/input-group"
import { SearchIcon } from "lucide-react"

export function ButtonGroupWithInputGroup() {
  return (
    <div className="flex flex-col gap-4">
      <InputGroup>
        <InputGroupInput placeholder="Type to search..." />
        <InputGroupAddon align="inline-start" className="text-muted-foreground">
          <SearchIcon />
        </InputGroupAddon>
      </InputGroup>
    </div>
  )
}

// apps/v4/registry/bases/vue/examples/button-group/ButtonGroupWithInputGroup.vue
<script setup lang="ts">
import IconPlaceholder from "@/components/IconPlaceholder.vue"
import {
  InputGroup,
  InputGroupAddon,
  InputGroupInput,
} from "@/ui/input-group"
import { Example } from "@/components/example"
</script>

<template>
  <Example title="With Input Group">
    <div class="flex flex-col gap-4">
      <InputGroup>
        <InputGroupInput placeholder="Type to search..." />
        <InputGroupAddon
          align="inline-start"
          class="text-muted-foreground"
        >
          <IconPlaceholder
            lucide="SearchIcon"
            tabler="IconSearch"
            hugeicons="Search01Icon"
            phosphor="MagnifyingGlassIcon"
            remixicon="RiSearchLine"
          />
        </InputGroupAddon>
      </InputGroup>
    </div>
  </Example>
</template>
