// apps/v4/styles/svelte-force-ui/ui/input-group/input-group.svelte
<script lang="ts">
  import { cn, type WithElementRef } from "$lib/utils.js"
  import type { HTMLAttributes } from "svelte/elements"
  import { tv } from "tailwind-variants"

  // [FORCE-UI-START]
  const inputGroupVariants = tv({
    base: "group/input-group relative flex w-full min-w-0 items-center outline-none h-9 has-[>textarea]:h-auto",
    variants: {
      variant: {
        outline:
          "cn-input-group-variant-outline border-input dark:bg-input/30 rounded-md border shadow-xs transition-[color,box-shadow]",
        filled: "cn-input-group-variant-filled",
        underline: "cn-input-group-variant-underline",
        ghost: "cn-input-group-variant-ghost",
      },
    },
    defaultVariants: {
      variant: "outline",
    },
  })
  // [FORCE-UI-END]

  let {
    ref = $bindable(null),
    class: className,
    variant = "outline",
    children,
    ...props
  }: WithElementRef<HTMLAttributes<HTMLDivElement>> & {
    variant?: "outline" | "filled" | "underline" | "ghost" // [FORCE-UI]
  } = $props()
</script>

<div
  bind:this={ref}
  data-slot="input-group"
  role="group"
  class={cn(inputGroupVariants({ variant }), className)}
  {...props}
>
  {@render children?.()}
</div>

// apps/v4/styles/vue-force-ui/ui/input-group/InputGroup.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue"

import { cn } from "@/lib/utils"

import { inputGroupVariants } from "."

const props = defineProps<{
  class?: HTMLAttributes["class"]
  variant?: "outline" | "filled" | "underline" | "ghost" // [FORCE-UI]
}>()
</script>

<template>
  <div
    data-slot="input-group"
    role="group"
    :class="
      cn(
        inputGroupVariants({ variant: props.variant }),

        // Variants based on alignment.
        'has-[>[data-align=inline-start]]:[&>input]:pl-2',
        'has-[>[data-align=inline-end]]:[&>input]:pr-2',
        'has-[>[data-align=block-start]]:h-auto has-[>[data-align=block-start]]:flex-col has-[>[data-align=block-start]]:[&>input]:pb-3',
        'has-[>[data-align=block-end]]:h-auto has-[>[data-align=block-end]]:flex-col has-[>[data-align=block-end]]:[&>input]:pt-3',

        // Focus state.
        'has-[[data-slot=input-group-control]:focus-visible]:border-ring has-[[data-slot=input-group-control]:focus-visible]:ring-[3px] has-[[data-slot=input-group-control]:focus-visible]:ring-ring/50',

        // Error state.
        'has-[[data-slot][aria-invalid=true]]:border-destructive has-[[data-slot][aria-invalid=true]]:ring-destructive/20 dark:has-[[data-slot][aria-invalid=true]]:ring-destructive/40',

        props.class
      )
    "
  >
    <slot />
  </div>
</template>
