// apps/v4/styles/svelte-lyra/ui/table/table-row.svelte
<script lang="ts">
  import { cn, type WithElementRef } from "$lib/utils.js"
  import type { HTMLAttributes } from "svelte/elements"

  let {
    ref = $bindable(null),
    class: className,
    children,
    ...restProps
  }: WithElementRef<HTMLAttributes<HTMLTableRowElement>> = $props()
</script>

<tr
  bind:this={ref}
  data-slot="table-row"
  class={cn("cn-table-row", className)}
  {...restProps}
>
  {@render children?.()}
</tr>

// apps/v4/registry/bases/vue/ui/table/TableRow.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue"
import { cn } from "@/lib/utils"

const props = defineProps<{
  class?: HTMLAttributes["class"]
}>()
</script>

<template>
  <tr
    data-slot="table-row"
    :class="cn('cn-table-row', props.class)"
  >
    <slot />
  </tr>
</template>
