// apps/v4/examples/base/textarea-with-label.tsx
import { Field, FieldLabel } from "@/examples/base/ui/field"
import { Textarea } from "@/examples/base/ui/textarea"

export function TextareaWithLabel() {
  return (
    <Field>
      <FieldLabel htmlFor="textarea-demo-message">Message</FieldLabel>
      <Textarea
        id="textarea-demo-message"
        placeholder="Type your message here."
        rows={6}
      />
    </Field>
  )
}

// apps/v4/registry/bases/vue/examples/textarea/TextareaWithLabel.vue
<script setup lang="ts">
import { Field, FieldLabel } from "@/ui/field"
import { Textarea } from "@/ui/textarea"
</script>

<template>
  <Field>
    <FieldLabel html-for="textarea-demo-message">
      Message
    </FieldLabel>
    <Textarea
      id="textarea-demo-message"
      placeholder="Type your message here."
      :rows="6"
    />
  </Field>
</template>
