// apps/v4/styles/vue-nova/ui/input-otp/InputOTPSeparator.vue
<script setup lang="ts">
import { useForwardProps } from "reka-ui"
import type { HTMLAttributes } from "vue"

import { IconPlaceholder } from "@/components/icon-placeholder"

const props = defineProps<{ class?: HTMLAttributes["class"] }>()

const forwarded = useForwardProps(props)
</script>

<template>
  <div data-slot="input-otp-separator" role="separator" v-bind="forwarded">
    <slot>
      <IconPlaceholder
        lucide="MinusIcon"
        tabler="IconMinus"
        hugeicons="Minus01Icon"
        phosphor="MinusIcon"
        remixicon="RiSubtractLine"
      />
    </slot>
  </div>
</template>

// apps/v4/preview-server/src/svelte-ui/input-otp/input-otp-separator.svelte
<script lang="ts">
	import type { HTMLAttributes } from "svelte/elements";
	import type { WithElementRef } from "@/svelte-lib/utils.js";
	import { cn } from "@/svelte-lib/utils.js";
	import IconPlaceholder from "@/svelte-components/icon-placeholder/icon-placeholder.svelte";

	let {
		ref = $bindable(null),
		class: className,
		children,
		...restProps
	}: WithElementRef<HTMLAttributes<HTMLDivElement>> = $props();
</script>

<div
	bind:this={ref}
	data-slot="input-otp-separator"
	role="separator"
	class={cn("cn-input-otp-separator flex items-center", className)}
	{...restProps}
>
	{#if children}
		{@render children?.()}
	{:else}
		<IconPlaceholder
			lucide="MinusIcon"
			tabler="IconMinus"
			hugeicons="MinusSignIcon"
			phosphor="MinusIcon"
			remixicon="RiSubtractLine"
		/>
	{/if}
</div>
