// apps/v4/registry/bases/vue/examples/input/InputWithText.vue
<script setup lang="ts">
import { Input } from '@/ui/input'
import { Label } from '@/ui/label'
</script>

<template>
  <div class="grid w-full max-w-sm items-center gap-1.5">
    <Label for="email">Email</Label>
    <Input id="email" type="email" placeholder="Email" />
    <p class="text-sm text-muted-foreground">
      Enter your email address.
    </p>
  </div>
</template>

// apps/v3/registry/new-york/examples/input-with-text.tsx
import { Input } from "@/registry/new-york/ui/input"
import { Label } from "@/registry/new-york/ui/label"

export default function InputWithText() {
  return (
    <div className="grid w-full max-w-sm items-center gap-1.5">
      <Label htmlFor="email-2">Email</Label>
      <Input type="email" id="email-2" placeholder="Email" />
      <p className="text-sm text-muted-foreground">Enter your email address.</p>
    </div>
  )
}
