// deprecated/www/registry/default/internal/sink/components/separator-demo.tsx
import { Separator } from "@/registry/default/ui/separator"

export function SeparatorDemo() {
  return (
    <div>
      <div className="space-y-1">
        <h4 className="text-sm font-medium leading-none">Radix Primitives</h4>
        <p className="text-sm text-muted-foreground">
          An open-source UI component library.
        </p>
      </div>
      <Separator className="my-4" />
      <div className="flex h-5 items-center space-x-4 text-sm">
        <div>Blog</div>
        <Separator orientation="vertical" />
        <div>Docs</div>
        <Separator orientation="vertical" />
        <div>Source</div>
      </div>
    </div>
  )
}

// apps/v4/registry/bases/svelte/examples/separator-demo.svelte
<script lang="ts">
	import { Separator } from "$lib/registry/ui/separator/index.js";
</script>

<div>
	<div class="space-y-1">
		<h4 class="text-sm leading-none font-medium">Bits UI Primitives</h4>
		<p class="text-muted-foreground text-sm">An open-source UI component library.</p>
	</div>
	<Separator class="my-4" />
	<div class="flex h-5 items-center space-x-4 text-sm">
		<div>Blog</div>
		<Separator orientation="vertical" />
		<div>Docs</div>
		<Separator orientation="vertical" />
		<div>Source</div>
	</div>
</div>
