// apps/v4/preview-server/src/ui/sidebar/SidebarTrigger.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue"
import { cn } from "@/lib/utils"
import IconPlaceholder from "@/components/IconPlaceholder.vue"
import { Button } from "@/ui/button"
import { useSidebar } from "./utils"

const props = defineProps<{
  class?: HTMLAttributes["class"]
}>()

const { toggleSidebar } = useSidebar()
</script>

<template>
  <Button
    data-sidebar="trigger"
    data-slot="sidebar-trigger"
    variant="ghost"
    size="icon-sm"
    :class="cn('cn-sidebar-trigger', props.class)"
    @click="toggleSidebar"
  >
    <IconPlaceholder
      lucide="PanelLeftIcon"
      tabler="IconLayoutSidebar"
      hugeicons="SidebarLeftIcon"
      phosphor="SidebarIcon"
      remixicon="RiSideBarLine"
    />
    <span class="sr-only">Toggle Sidebar</span>
  </Button>
</template>

// apps/v4/preview-server/src/svelte-ui/sidebar/sidebar-trigger.svelte
<script lang="ts">
	import { Button } from "@/svelte-ui/button/index.js";
	import IconPlaceholder from "@/svelte-components/icon-placeholder/icon-placeholder.svelte";
	import { cn } from "@/svelte-lib/utils.js";
	import type { ComponentProps } from "svelte";
	import { useSidebar } from "./context.svelte.js";

	let {
		ref = $bindable(null),
		class: className,
		onclick,
		...restProps
	}: ComponentProps<typeof Button> & {
		onclick?: (e: MouseEvent) => void;
	} = $props();

	const sidebar = useSidebar();
</script>

<Button
	bind:ref
	data-sidebar="trigger"
	data-slot="sidebar-trigger"
	variant="ghost"
	size="icon-sm"
	class={cn("cn-sidebar-trigger", className)}
	type="button"
	onclick={(e) => {
		onclick?.(e);
		sidebar.toggle();
	}}
	{...restProps}
>
	<IconPlaceholder
		lucide="PanelLeftIcon"
		tabler="IconLayoutSidebar"
		hugeicons="SidebarLeftIcon"
		phosphor="SidebarIcon"
		remixicon="RiSideBarLine"
	/>
	<span class="sr-only">Toggle Sidebar</span>
</Button>
