// apps/v4/examples/base/native-select-groups.tsx
import {
  NativeSelect,
  NativeSelectOptGroup,
  NativeSelectOption,
} from "@/examples/base/ui/native-select"

export default function NativeSelectGroups() {
  return (
    <NativeSelect>
      <NativeSelectOption value="">Select department</NativeSelectOption>
      <NativeSelectOptGroup label="Engineering">
        <NativeSelectOption value="frontend">Frontend</NativeSelectOption>
        <NativeSelectOption value="backend">Backend</NativeSelectOption>
        <NativeSelectOption value="devops">DevOps</NativeSelectOption>
      </NativeSelectOptGroup>
      <NativeSelectOptGroup label="Sales">
        <NativeSelectOption value="sales-rep">Sales Rep</NativeSelectOption>
        <NativeSelectOption value="account-manager">
          Account Manager
        </NativeSelectOption>
        <NativeSelectOption value="sales-director">
          Sales Director
        </NativeSelectOption>
      </NativeSelectOptGroup>
      <NativeSelectOptGroup label="Operations">
        <NativeSelectOption value="support">
          Customer Support
        </NativeSelectOption>
        <NativeSelectOption value="product-manager">
          Product Manager
        </NativeSelectOption>
        <NativeSelectOption value="ops-manager">
          Operations Manager
        </NativeSelectOption>
      </NativeSelectOptGroup>
    </NativeSelect>
  )
}

// apps/v4/preview-server/src/svelte/native-select-groups.svelte
<script lang="ts">
	import * as NativeSelect from "@/svelte-ui/native-select/index.js";
</script>

<NativeSelect.Root>
	<NativeSelect.Option value="">Select department</NativeSelect.Option>
	<NativeSelect.OptGroup label="Engineering">
		<NativeSelect.Option value="frontend">Frontend</NativeSelect.Option>
		<NativeSelect.Option value="backend">Backend</NativeSelect.Option>
		<NativeSelect.Option value="devops">DevOps</NativeSelect.Option>
	</NativeSelect.OptGroup>
	<NativeSelect.OptGroup label="Sales">
		<NativeSelect.Option value="sales-rep">Sales Rep</NativeSelect.Option>
		<NativeSelect.Option value="account-manager">Account Manager</NativeSelect.Option>
		<NativeSelect.Option value="sales-director">Sales Director</NativeSelect.Option>
	</NativeSelect.OptGroup>
	<NativeSelect.OptGroup label="Operations">
		<NativeSelect.Option value="support">Customer Support</NativeSelect.Option>
		<NativeSelect.Option value="product-manager">Product Manager</NativeSelect.Option>
		<NativeSelect.Option value="ops-manager">Operations Manager</NativeSelect.Option>
	</NativeSelect.OptGroup>
</NativeSelect.Root>
