// apps/v4/styles/vue-force-ui/ui/carousel/CarouselPrevious.vue
<script setup lang="ts">
import type { ButtonVariants } from "@/ui/button"
import { Button } from "@/ui/button"

import { cn } from "@/lib/utils"
import { IconPlaceholder } from "@/components/icon-placeholder"

import type { WithClassAsProps } from "./interface"
import { useCarousel } from "./useCarousel"

const props = withDefaults(
  defineProps<
    {
      variant?: ButtonVariants["variant"]
      size?: ButtonVariants["size"]
    } & WithClassAsProps
  >(),
  {
    variant: "outline",
    size: "icon",
  }
)

const { orientation, canScrollPrev, scrollPrev } = useCarousel()
</script>

<template>
  <Button
    data-slot="carousel-previous"
    :disabled="!canScrollPrev"
    :class="
      cn(
        'absolute size-8 rounded-full',
        orientation === 'horizontal'
          ? 'top-1/2 -left-12 -translate-y-1/2'
          : '-top-12 left-1/2 -translate-x-1/2 rotate-90',
        props.class
      )
    "
    :variant="variant"
    :size="size"
    @click="scrollPrev"
  >
    <slot>
      <IconPlaceholder
        lucide="ArrowLeftIcon"
        materialSymbols="arrow_left"
        tabler="IconArrowLeft"
        hugeicons="ArrowLeft01Icon"
        phosphor="ArrowLeftIcon"
        remixicon="RiArrowLeftLine"
      />
      <span class="sr-only">Previous Slide</span>
    </slot>
  </Button>
</template>

// apps/v4/styles/svelte-force-ui/ui/carousel/carousel-previous.svelte
<script lang="ts">
  import IconPlaceholder from "$lib/components/icon-placeholder/icon-placeholder.svelte"
  import { Button, type Props } from "$lib/registry/ui/button/index.js"
  import { cn } from "$lib/utils.js"
  import type { WithoutChildren } from "bits-ui"

  import { getEmblaContext } from "./context.js"

  let {
    ref = $bindable(null),
    class: className,
    variant = "outline",
    size = "icon-sm",
    ...restProps
  }: WithoutChildren<Props> = $props()

  const emblaCtx = getEmblaContext("<Carousel.Previous/>")
</script>

<Button
  data-slot="carousel-previous"
  {variant}
  {size}
  aria-disabled={!emblaCtx.canScrollPrev}
  disabled={!emblaCtx.canScrollPrev}
  class={cn(
    "cn-carousel-previous absolute touch-manipulation",
    emblaCtx.orientation === "horizontal"
      ? "-start-12 top-1/2 -translate-y-1/2"
      : "start-1/2 -top-12 -translate-x-1/2 rotate-90",
    className
  )}
  onclick={emblaCtx.scrollPrev}
  onkeydown={emblaCtx.handleKeyDown}
  {...restProps}
  bind:ref
>
  <IconPlaceholder
    lucide="ChevronLeftIcon"
    materialSymbols="chevron_left"
    tabler="IconChevronLeft"
    hugeicons="ArrowLeft01Icon"
    phosphor="CaretLeftIcon"
    remixicon="RiArrowLeftSLine"
  />
  <span class="sr-only">Previous slide</span>
</Button>
