// apps/preview-svelte/src/svelte/demo-sidebar-controlled.svelte
<script lang="ts">
	import * as Sidebar from "@/svelte-ui/sidebar/index.js";
	import { Button } from "@/svelte-ui/button/index.js";
	import PanelLeftOpenIcon from "~icons/ms/left_panel_open";
	import PanelLeftCloseIcon from "~icons/ms/left_panel_close";
	import LifeBuoyIcon from "~icons/ms/support";
	import SendIcon from "~icons/ms/send";
	import FrameIcon from "~icons/ms/crop_square";
	import ChartPieIcon from "~icons/ms/pie_chart";
	import MapIcon from "~icons/ms/map";

	const projects = [
		{
			name: "Design Engineering",
			url: "#",
			icon: FrameIcon,
		},
		{
			name: "Sales & Marketing",
			url: "#",
			icon: ChartPieIcon,
		},
		{
			name: "Travel",
			url: "#",
			icon: MapIcon,
		},
		{
			name: "Support",
			url: "#",
			icon: LifeBuoyIcon,
		},
		{
			name: "Feedback",
			url: "#",
			icon: SendIcon,
		},
	];

	let open = $state(true);
</script>

<Sidebar.Provider bind:open={() => open, (v) => (open = v)}>
	<Sidebar.Root>
		<Sidebar.Content>
			<Sidebar.Group>
				<Sidebar.GroupLabel>Projects</Sidebar.GroupLabel>
				<Sidebar.GroupContent>
					<Sidebar.Menu>
						{#each projects as project (project.name)}
							<Sidebar.MenuItem>
								<Sidebar.MenuButton>
									{#snippet child({ props })}
										<a href={project.url} {...props}>
											<project.icon />
											<span>{project.name}</span>
										</a>
									{/snippet}
								</Sidebar.MenuButton>
							</Sidebar.MenuItem>
						{/each}
					</Sidebar.Menu>
				</Sidebar.GroupContent>
			</Sidebar.Group>
		</Sidebar.Content>
	</Sidebar.Root>
	<Sidebar.Inset>
		<header class="flex h-12 items-center justify-between px-4">
			<Button onclick={() => (open = !open)} size="sm" variant="ghost">
				{#if open}
					<PanelLeftCloseIcon />
				{:else}
					<PanelLeftOpenIcon />
				{/if}
				<span>{open ? "Close" : "Open"} Sidebar</span>
			</Button>
		</header>
	</Sidebar.Inset>
</Sidebar.Provider>

// apps/www/registry/default/block/demo-sidebar-controlled.tsx
"use client"

import * as React from "react"
import {
  Frame,
  LifeBuoy,
  Map,
  PanelLeftClose,
  PanelLeftOpen,
  PieChart,
  Send,
} from "lucide-react"

import { Button } from "@/registry/default/ui/button"
import {
  Sidebar,
  SidebarContent,
  SidebarGroup,
  SidebarGroupContent,
  SidebarGroupLabel,
  SidebarInset,
  SidebarMenu,
  SidebarMenuButton,
  SidebarMenuItem,
  SidebarProvider,
} from "@/registry/default/ui/sidebar"

const projects = [
  {
    name: "Design Engineering",
    url: "#",
    icon: Frame,
  },
  {
    name: "Sales & Marketing",
    url: "#",
    icon: PieChart,
  },
  {
    name: "Travel",
    url: "#",
    icon: Map,
  },
  {
    name: "Support",
    url: "#",
    icon: LifeBuoy,
  },
  {
    name: "Feedback",
    url: "#",
    icon: Send,
  },
]

export default function AppSidebar() {
  const [open, setOpen] = React.useState(true)

  return (
    <SidebarProvider open={open} onOpenChange={setOpen}>
      <Sidebar>
        <SidebarContent>
          <SidebarGroup>
            <SidebarGroupLabel>Projects</SidebarGroupLabel>
            <SidebarGroupContent>
              <SidebarMenu>
                {projects.map((project) => (
                  <SidebarMenuItem key={project.name}>
                    <SidebarMenuButton asChild>
                      <a href={project.url}>
                        <project.icon />
                        <span>{project.name}</span>
                      </a>
                    </SidebarMenuButton>
                  </SidebarMenuItem>
                ))}
              </SidebarMenu>
            </SidebarGroupContent>
          </SidebarGroup>
        </SidebarContent>
      </Sidebar>
      <SidebarInset>
        <header className="flex items-center h-12 px-4 justify-between">
          <Button
            onClick={() => setOpen((open) => !open)}
            size="sm"
            variant="ghost"
          >
            {open ? <PanelLeftClose /> : <PanelLeftOpen />}
            <span>{open ? "Open" : "Close"} Sidebar</span>
          </Button>
        </header>
      </SidebarInset>
    </SidebarProvider>
  )
}
