// apps/v4/styles/vue-force-ui/ui/navigation-menu/NavigationMenuTrigger.vue
<script setup lang="ts">
import { reactiveOmit } from "@vueuse/core"
import type { NavigationMenuTriggerProps } from "reka-ui"
import { NavigationMenuTrigger, useForwardProps } from "reka-ui"
import type { HTMLAttributes } from "vue"

import { cn } from "@/lib/utils"
import { IconPlaceholder } from "@/components/icon-placeholder"

import { navigationMenuTriggerStyle } from "."

const props = defineProps<
  NavigationMenuTriggerProps & { class?: HTMLAttributes["class"] }
>()

const delegatedProps = reactiveOmit(props, "class")

const forwardedProps = useForwardProps(delegatedProps)
</script>

<template>
  <NavigationMenuTrigger
    data-slot="navigation-menu-trigger"
    v-bind="forwardedProps"
    :class="cn(navigationMenuTriggerStyle(), 'group', props.class)"
  >
    <slot />
    <IconPlaceholder
      lucide="ChevronDownIcon"
      materialSymbols="keyboard_arrow_down"
      tabler="IconChevronDown"
      hugeicons="ArrowDown01Icon"
      phosphor="CaretDownIcon"
      remixicon="RiArrowDownSLine"
      class="cn-navigation-menu-trigger-icon"
      aria-hidden="true"
    />
  </NavigationMenuTrigger>
</template>

// packages/registry-svelte/ui/navigation-menu/navigation-menu-trigger.svelte
<script lang="ts" module>
	import { cn } from "$lib/utils.js";
	import { tv } from "tailwind-variants";

	export const navigationMenuTriggerStyle = tv({
		base: "cn-navigation-menu-trigger group/navigation-menu-trigger inline-flex h-9 w-max items-center justify-center outline-none disabled:pointer-events-none",
	});
</script>

<script lang="ts">
	import { NavigationMenu as NavigationMenuPrimitive } from "bits-ui";
	import IconPlaceholder from "$lib/components/icon-placeholder/icon-placeholder.svelte";
	let {
		ref = $bindable(null),
		class: className,
		children,
		...restProps
	}: NavigationMenuPrimitive.TriggerProps = $props();
</script>

<NavigationMenuPrimitive.Trigger
	bind:ref
	data-slot="navigation-menu-trigger"
	class={cn(navigationMenuTriggerStyle(), "group", className)}
	{...restProps}
>
	{@render children?.()}
	<IconPlaceholder
		lucide="ChevronDownIcon"
		materialSymbols="keyboard_arrow_down"
		tabler="IconChevronDown"
		hugeicons="ArrowDown01Icon"
		phosphor="CaretDownIcon"
		remixicon="RiArrowDownSLine"
		class="cn-navigation-menu-trigger-icon"
		aria-hidden="true"
	/>
</NavigationMenuPrimitive.Trigger>
