// apps/v4/styles/svelte-vega/ui/select/select-scroll-up-button.svelte
<script lang="ts">
  import IconPlaceholder from "$lib/components/icon-placeholder/icon-placeholder.svelte"
  import { cn, type WithoutChildrenOrChild } from "$lib/utils.js"
  import { Select as SelectPrimitive } from "bits-ui"

  let {
    ref = $bindable(null),
    class: className,
    ...restProps
  }: WithoutChildrenOrChild<SelectPrimitive.ScrollUpButtonProps> = $props()
</script>

<SelectPrimitive.ScrollUpButton
  bind:ref
  data-slot="select-scroll-up-button"
  class={cn("cn-select-scroll-up-button top-0 w-full", className)}
  {...restProps}
>
  <IconPlaceholder
    lucide="ChevronUpIcon"
    tabler="IconChevronUp"
    hugeicons="ArrowUp01Icon"
    phosphor="CaretUpIcon"
    remixicon="RiArrowUpSLine"
  />
</SelectPrimitive.ScrollUpButton>

// apps/v4/registry/bases/vue/ui/select/SelectScrollUpButton.vue
<script setup lang="ts">
import type { SelectScrollUpButtonProps } from "reka-ui"
import type { HTMLAttributes } from "vue"
import { reactiveOmit } from "@vueuse/core"
import { SelectScrollUpButton, useForwardProps } from "reka-ui"
import { cn } from "@/lib/utils"
import IconPlaceholder from "@/components/icon-placeholder/IconPlaceholder.vue"

const props = defineProps<SelectScrollUpButtonProps & { class?: HTMLAttributes["class"] }>()

const delegatedProps = reactiveOmit(props, "class")

const forwardedProps = useForwardProps(delegatedProps)
</script>

<template>
  <SelectScrollUpButton
    data-slot="select-scroll-up-button"
    v-bind="forwardedProps"
    :class="cn('cn-select-scroll-up-button', props.class)"
  >
    <slot>
      <IconPlaceholder
        lucide="ChevronUpIcon"
        tabler="IconChevronUp"
        hugeicons="ArrowUp01Icon"
        phosphor="CaretUpIcon"
        remixicon="RiArrowUpSLine"
      />
    </slot>
  </SelectScrollUpButton>
</template>
