// apps/v4/examples/base/switch-basic.tsx
import { Field, FieldLabel } from "@/examples/base/ui/field"
import { Switch } from "@/examples/base/ui/switch"

export function SwitchBasic() {
  return (
    <Field orientation="horizontal">
      <Switch id="switch-basic" />
      <FieldLabel htmlFor="switch-basic">Airplane Mode</FieldLabel>
    </Field>
  )
}

// apps/v4/registry/bases/vue/examples/switch/SwitchBasic.vue
<script setup lang="ts">
import { Field, FieldLabel } from "@/ui/field"
import { Switch } from "@/ui/switch"
</script>

<template>
  <Field orientation="horizontal">
    <Switch id="switch-basic" />
    <FieldLabel html-for="switch-basic">
      Airplane Mode
    </FieldLabel>
  </Field>
</template>
