// apps/v4/preview-server/src/ui/input-group/InputGroupInput.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue"
import { cn } from "@/lib/utils"
import { Input } from "@/registry/new-york-v4/ui/input"

const props = defineProps<{
  class?: HTMLAttributes["class"]
}>()
</script>

<template>
  <Input
    data-slot="input-group-control"
    :class="cn(
      'flex-1 rounded-none border-0 bg-transparent shadow-none focus-visible:ring-0 dark:bg-transparent',
      props.class,
    )"
  />
</template>

// apps/v4/styles/svelte-nova/ui/input-group/input-group-input.svelte
<script lang="ts">
  import { Input } from "$lib/registry/ui/input/index.js"
  import { cn } from "$lib/utils.js"
  import type { ComponentProps } from "svelte"

  let {
    ref = $bindable(null),
    value = $bindable(),
    class: className,
    ...props
  }: ComponentProps<typeof Input> = $props()
</script>

<Input
  bind:ref
  data-slot="input-group-control"
  class={cn("cn-input-group-input flex-1", className)}
  bind:value
  {...props}
/>
