// apps/v4/preview-server/src/ui/pagination/PaginationLink.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue"
import type { ButtonVariants } from "@/registry/bases/reka/ui/button"
import { cn } from "@/lib/utils"
import { buttonVariants } from "@/registry/bases/reka/ui/button"

const props = withDefaults(defineProps<{
  href?: string
  size?: ButtonVariants["size"]
  isActive?: boolean
  class?: HTMLAttributes["class"]
}>(), {
  size: "icon",
  isActive: false,
})
</script>

<template>
  <a
    :href="href"
    data-slot="pagination-link"
    :data-active="isActive"
    :aria-current="isActive ? 'page' : undefined"
    :class="cn(
      buttonVariants({
        variant: isActive ? 'outline' : 'ghost',
        size,
      }),
      'cn-pagination-link',
      props.class,
    )"
  >
    <slot />
  </a>
</template>

// apps/v4/styles/svelte-mira/ui/pagination/pagination-link.svelte
<script lang="ts">
  import {
    buttonVariants,
    type ButtonSize,
  } from "$lib/registry/ui/button/index.js"
  import { cn } from "$lib/utils.js"
  import { Pagination as PaginationPrimitive } from "bits-ui"

  let {
    ref = $bindable(null),
    class: className,
    size = "icon",
    isActive,
    page,
    children,
    ...restProps
  }: PaginationPrimitive.PageProps & {
    size?: ButtonSize
    isActive: boolean
  } = $props()
</script>

{#snippet Fallback()}
  {page.value}
{/snippet}

<PaginationPrimitive.Page
  bind:ref
  {page}
  aria-current={isActive ? "page" : undefined}
  data-slot="pagination-link"
  data-active={isActive}
  data-size={size}
  class={cn(
    buttonVariants({ size, variant: isActive ? "outline" : "ghost" }),
    "cn-pagination-link",
    className
  )}
  {...restProps}
>
  {#if children}
    {@render children?.()}
  {:else}
    {@render Fallback()}
  {/if}
</PaginationPrimitive.Page>
