// apps/v4/preview-server/src/vue/CalendarCustomDays.vue
<script setup lang="ts">
import type { DateRange } from "reka-ui"
import { CalendarDate } from "@internationalized/date"
import { ref } from "vue"
import { Card, CardContent } from "@/ui/card"
import { RangeCalendar } from "@/ui/range-calendar"
import { Example } from "@/components"

const range = ref<DateRange>({
  start: new CalendarDate(new Date().getFullYear(), 12, 8),
  end: new CalendarDate(new Date().getFullYear(), 12, 18),
})

function isWeekend(date: CalendarDate) {
  const jsDate = new Date(date.year, date.month - 1, date.day)
  const dayOfWeek = jsDate.getDay()
  return dayOfWeek === 0 || dayOfWeek === 6
}

function getPrice(date: CalendarDate) {
  return isWeekend(date) ? "$120" : "$100"
}
</script>

<template>
  <Example title="Custom Days">
    <Card class="mx-auto w-fit p-0">
      <CardContent class="p-0">
        <RangeCalendar
          v-model="range"
          :number-of-months="1"
          layout="month-and-year"
          class="[--rdp-cell-size:theme(spacing.10)] md:[--rdp-cell-size:theme(spacing.12)]"
        >
          <template #calendar-cell="{ date }">
            <div class="flex flex-col items-center justify-center h-full">
              <span>{{ date.day }}</span>
              <span class="text-xs text-muted-foreground">{{ getPrice(date) }}</span>
            </div>
          </template>
        </RangeCalendar>
      </CardContent>
    </Card>
  </Example>
</template>

// apps/v4/examples/aria/calendar-custom-days.tsx
"use client"

import * as React from "react"
import { CalendarDate, isWeekend } from "@internationalized/date"
import { useLocale, type DateRange } from "react-aria-components"

import { RangeCalendar } from "@/styles/aria-nova/ui/calendar"
import { Card, CardContent } from "@/styles/aria-nova/ui/card"

export function CalendarCustomDays() {
  const { locale } = useLocale()
  const [range, setRange] = React.useState<DateRange | undefined>({
    start: new CalendarDate(new Date().getFullYear(), 12, 8),
    end: new CalendarDate(new Date().getFullYear(), 12, 8).add({ days: 10 }),
  })

  return (
    <Card className="mx-auto w-fit p-0">
      <CardContent className="p-0">
        <RangeCalendar
          value={range}
          onChange={setRange}
          numberOfMonths={1}
          captionLayout="dropdown"
          className="[--cell-size:--spacing(10)] md:[--cell-size:--spacing(12)]"
          headerFormat={{ month: "long" }}
          renderCell={({ isOutsideMonth, date, defaultChildren }) => (
            <>
              {defaultChildren}
              {!isOutsideMonth && (
                <span>{isWeekend(date, locale) ? "$120" : "$100"}</span>
              )}
            </>
          )}
        />
      </CardContent>
    </Card>
  )
}
