// apps/preview-vue/src/vue/progress-label.vue
<script setup lang="ts">
import { Field, FieldLabel } from '@/ui/field'
import { Progress } from '@/ui/progress'
</script>

<template>
  <Field class="w-full max-w-sm">
    <FieldLabel for="progress-upload">
      <span>Upload progress</span>
      <span class="ml-auto">66%</span>
    </FieldLabel>
    <Progress :model-value="66" id="progress-upload" />
  </Field>
</template>

// apps/preview-svelte/src/svelte/progress-label.svelte
<script lang="ts">
	import * as Field from "@/svelte-ui/field/index.js";
	import { Progress } from "@/svelte-ui/progress/index.js";
</script>

<Field.Field class="w-full max-w-sm">
	<Field.Label for="progress-upload">
		<span>Upload progress</span>
		<span class="ml-auto">66%</span>
	</Field.Label>
	<Progress value={66} id="progress-upload" />
</Field.Field>
