// apps/preview-vue/src/vue/scroll-area-rtl.vue
<script setup lang="ts">
import { ScrollArea } from '@/ui/scroll-area'
import { Separator } from '@/ui/separator'

const tags = Array.from({ length: 50 }).map(
  (_, i, a) => `v1.2.0-beta.${a.length - i}`,
)
</script>

<template>
  <ScrollArea class="h-72 w-48 rounded-md border" dir="rtl">
    <div class="p-4">
      <h4 class="mb-4 text-sm leading-none font-medium">
        العلامات
      </h4>
      <template v-for="tag in tags" :key="tag">
        <div class="text-sm">
          {{ tag }}
        </div>
        <Separator class="my-2" />
      </template>
    </div>
  </ScrollArea>
</template>

// apps/preview-svelte/src/svelte/scroll-area-rtl.svelte
<script lang="ts">
	import { ScrollArea } from "@/svelte-ui/scroll-area/index.js";
	import { Separator } from "@/svelte-ui/separator/index.js";

	const tags = Array.from({ length: 50 }).map((_, i, a) => `v1.2.0-beta.${a.length - i}`);
</script>

<ScrollArea class="h-72 w-48 rounded-md border" dir="rtl">
	<div class="p-4">
		<h4 class="mb-4 text-sm leading-none font-medium">العلامات</h4>
		{#each tags as tag (tag)}
			<div class="text-sm">
				{tag}
			</div>
			<Separator class="my-2" />
		{/each}
	</div>
</ScrollArea>
