// apps/v4/examples/react-aria/sheet-no-close-button.tsx
import { Button } from "@/examples/react-aria/ui/button"
import {
  Sheet,
  SheetDescription,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from "@/examples/react-aria/ui/sheet"

export default function SheetNoCloseButton() {
  return (
    <SheetTrigger>
      <Button variant="outline">Open Sheet</Button>
      <Sheet showCloseButton={false}>
        <SheetHeader>
          <SheetTitle>No Close Button</SheetTitle>
          <SheetDescription>
            This sheet doesn&apos;t have a close button in the top-right corner.
            Click outside to close.
          </SheetDescription>
        </SheetHeader>
      </Sheet>
    </SheetTrigger>
  )
}

// apps/preview-svelte/src/svelte/sheet-no-close-button.svelte
<script lang="ts">
	import { buttonVariants } from "@/svelte-ui/button/index.js";
	import * as Sheet from "@/svelte-ui/sheet/index.js";
</script>

<Sheet.Root>
	<Sheet.Trigger class={buttonVariants({ variant: "outline" })}>Open Sheet</Sheet.Trigger>
	<Sheet.Content showCloseButton={false}>
		<Sheet.Header>
			<Sheet.Title>No Close Button</Sheet.Title>
			<Sheet.Description>
				This sheet doesn't have a close button in the top-right corner.
				Click outside to close.
			</Sheet.Description>
		</Sheet.Header>
	</Sheet.Content>
</Sheet.Root>
