// apps/www/registry/default/example/toggle-group-disabled.tsx
import { Bold, Italic, Strikethrough } from "lucide-react"

import { ToggleGroup, ToggleGroupItem } from "../ui/toggle-group"

export default function ToggleGroupDemo() {
  return (
    <ToggleGroup disabled type="single">
      <ToggleGroupItem value="bold" aria-label="Toggle bold">
        <Bold className="h-4 w-4" />
      </ToggleGroupItem>
      <ToggleGroupItem value="italic" aria-label="Toggle italic">
        <Italic className="h-4 w-4" />
      </ToggleGroupItem>
      <ToggleGroupItem value="strikethrough" aria-label="Toggle strikethrough">
        <Strikethrough className="h-4 w-4" />
      </ToggleGroupItem>
    </ToggleGroup>
  )
}

// apps/preview-svelte/src/svelte/toggle-group-disabled.svelte
<script lang="ts">
	import BoldIcon from "~icons/ms/format_bold";
	import ItalicIcon from "~icons/ms/format_italic";
	import UnderlineIcon from "~icons/ms/format_underlined";
	import * as ToggleGroup from "@/svelte-ui/toggle-group/index.js";
</script>

<ToggleGroup.Root disabled type="single">
	<ToggleGroup.Item value="bold" aria-label="Toggle bold">
		<BoldIcon class="size-4" />
	</ToggleGroup.Item>
	<ToggleGroup.Item value="italic" aria-label="Toggle italic">
		<ItalicIcon class="size-4" />
	</ToggleGroup.Item>
	<ToggleGroup.Item value="strikethrough" aria-label="Toggle strikethrough">
		<UnderlineIcon class="size-4" />
	</ToggleGroup.Item>
</ToggleGroup.Root>
