// apps/v4/preview-server/src/svelte-ui/label/label.svelte
<script lang="ts">
	import { Label as LabelPrimitive } from "bits-ui";
	import { cn } from "@/svelte-lib/utils.js";

	let {
		ref = $bindable(null),
		class: className,
		...restProps
	}: LabelPrimitive.RootProps = $props();
</script>

<LabelPrimitive.Root
	bind:ref
	data-slot="label"
	class={cn(
		"cn-label flex items-center select-none group-data-[disabled=true]:pointer-events-none peer-disabled:cursor-not-allowed",
		className
	)}
	{...restProps}
/>

// apps/v4/registry/bases/react-aria/ui/label.tsx
"use client"

import * as React from "react"
import { Label as LabelPrimitive } from "react-aria-components"

import { cn } from "@/registry/bases/react-aria/lib/utils"

function Label({ className, ...props }: React.ComponentProps<"label">) {
  return (
    <LabelPrimitive
      data-slot="label"
      className={cn(
        "cn-label flex items-center select-none group-data-[disabled=true]:pointer-events-none peer-disabled:cursor-not-allowed",
        className
      )}
      {...props}
    />
  )
}

export { Label }
