// apps/v4/examples/base/badge-solid.tsx
import { Badge } from "@/styles/base-force-ui/ui/badge"

export function BadgeSolid() {
  return (
    <div className="flex flex-wrap gap-2">
      <Badge variant="success-solid">Success</Badge>
      <Badge variant="warning-solid">Warning</Badge>
      <Badge variant="info-solid">Info</Badge>
      <Badge variant="error-solid">Error</Badge>
    </div>
  )
}

// packages/registry-svelte/examples/badge-solid.svelte
<script lang="ts">
	import { Badge } from "$lib/registry/ui/badge/index.js";
</script>

<div class="flex flex-wrap gap-2">
	<Badge variant="success-solid">Success</Badge>
	<Badge variant="warning-solid">Warning</Badge>
	<Badge variant="info-solid">Info</Badge>
	<Badge variant="error-solid">Error</Badge>
</div>
