// apps/v4/examples/ark/toggle-group-spacing.tsx
import { ToggleGroup, ToggleGroupItem } from "@/examples/ark/ui/toggle-group"

export function ToggleGroupSpacing() {
  return (
    <ToggleGroup
      type="single"
      size="sm"
      defaultValue="top"
      variant="outline"
      spacing={2}
    >
      <ToggleGroupItem value="top" aria-label="Toggle top">
        Top
      </ToggleGroupItem>
      <ToggleGroupItem value="bottom" aria-label="Toggle bottom">
        Bottom
      </ToggleGroupItem>
      <ToggleGroupItem value="left" aria-label="Toggle left">
        Left
      </ToggleGroupItem>
      <ToggleGroupItem value="right" aria-label="Toggle right">
        Right
      </ToggleGroupItem>
    </ToggleGroup>
  )
}

// apps/v4/registry/bases/vue/examples/toggle-group/ToggleGroupSpacing.vue
<script setup lang="ts">
import { ToggleGroup, ToggleGroupItem } from "@/ui/toggle-group"
</script>

<template>
  <ToggleGroup
    type="single"
    size="sm"
    default-value="top"
    variant="outline"
    :spacing="2"
  >
    <ToggleGroupItem value="top" aria-label="Toggle top">
      Top
    </ToggleGroupItem>
    <ToggleGroupItem value="bottom" aria-label="Toggle bottom">
      Bottom
    </ToggleGroupItem>
    <ToggleGroupItem value="left" aria-label="Toggle left">
      Left
    </ToggleGroupItem>
    <ToggleGroupItem value="right" aria-label="Toggle right">
      Right
    </ToggleGroupItem>
  </ToggleGroup>
</template>
