// apps/v4/preview-server/src/svelte-ui/menubar/menubar-trigger.svelte
<script lang="ts">
	import { Menubar as MenubarPrimitive } from "bits-ui";
	import { cn } from "@/svelte-lib/utils.js";

	let {
		ref = $bindable(null),
		class: className,
		...restProps
	}: MenubarPrimitive.TriggerProps = $props();
</script>

<MenubarPrimitive.Trigger
	bind:ref
	data-slot="menubar-trigger"
	class={cn("cn-menubar-trigger flex items-center outline-hidden select-none", className)}
	{...restProps}
/>

// apps/v4/styles/vue-nova/ui/menubar/MenubarTrigger.vue
<script setup lang="ts">
import { reactiveOmit } from "@vueuse/core"
import type { MenubarTriggerProps } from "reka-ui"
import { MenubarTrigger, useForwardProps } from "reka-ui"
import type { HTMLAttributes } from "vue"

import { cn } from "@/lib/utils"

const props = defineProps<
  MenubarTriggerProps & { class?: HTMLAttributes["class"] }
>()

const delegatedProps = reactiveOmit(props, "class")

const forwardedProps = useForwardProps(delegatedProps)
</script>

<template>
  <MenubarTrigger
    data-slot="menubar-trigger"
    v-bind="forwardedProps"
    :class="
      cn(
        'cn-menubar-trigger flex items-center outline-hidden select-none',
        props.class
      )
    "
  >
    <slot />
  </MenubarTrigger>
</template>
