// apps/v4/preview-server/src/vue/ComboboxInvalid.vue
<script setup lang="ts">
import { Example } from "@/components"
import {
  Combobox,
  ComboboxEmpty,
  ComboboxInput,
  ComboboxItem,
  ComboboxList,
  ComboboxViewport,
} from "@/ui/combobox"
import {
  Field,
  FieldDescription,
  FieldError,
  FieldLabel,
} from "@/ui/field"

const frameworks = [
  "Next.js",
  "SvelteKit",
  "Nuxt.js",
  "Remix",
  "Astro",
]
</script>

<template>
  <Example title="Invalid">
    <div class="flex flex-col gap-4">
      <Combobox :items="frameworks">
        <ComboboxInput
          placeholder="Select a framework"
          :aria-invalid="true"
        />
        <ComboboxList>
          <ComboboxViewport>
            <ComboboxEmpty>No items found.</ComboboxEmpty>
            <ComboboxItem
              v-for="item in frameworks"
              :key="item"
              :value="item"
            >
              {{ item }}
            </ComboboxItem>
          </ComboboxViewport>
        </ComboboxList>
      </Combobox>
      <Field data-invalid>
        <FieldLabel html-for="combobox-framework-invalid">
          Framework
        </FieldLabel>
        <Combobox :items="frameworks">
          <ComboboxInput
            id="combobox-framework-invalid"
            placeholder="Select a framework"
            :aria-invalid="true"
          />
          <ComboboxList>
            <ComboboxViewport>
              <ComboboxEmpty>No items found.</ComboboxEmpty>
              <ComboboxItem
                v-for="item in frameworks"
                :key="item"
                :value="item"
              >
                {{ item }}
              </ComboboxItem>
            </ComboboxViewport>
          </ComboboxList>
        </Combobox>
        <FieldDescription>Please select a valid framework.</FieldDescription>
        <FieldError :errors="[{ message: 'This field is required.' }]" />
      </Field>
    </div>
  </Example>
</template>

// apps/v4/examples/base/combobox-invalid.tsx
import {
  Combobox,
  ComboboxContent,
  ComboboxEmpty,
  ComboboxInput,
  ComboboxItem,
  ComboboxList,
} from "@/examples/base/ui/combobox"
import {
  Field,
  FieldDescription,
  FieldError,
  FieldLabel,
} from "@/examples/base/ui/field"
import { Select } from "@/examples/base/ui/select"

const frameworks = [
  "Next.js",
  "SvelteKit",
  "Nuxt.js",
  "Remix",
  "Astro",
] as const

const items = [
  {
    label: "Select a framework",
    value: null,
  },
  {
    label: "React",
    value: "react",
  },
  {
    label: "Vue",
    value: "vue",
  },
  {
    label: "Angular",
    value: "angular",
  },
  {
    label: "Svelte",
    value: "svelte",
  },
  {
    label: "Solid",
    value: "solid",
  },
  {
    label: "Preact",
    value: "preact",
  },
  {
    label: "Next.js",
    value: "next.js",
  },
]

export function ComboboxInvalid() {
  return (
    <div className="flex flex-col gap-4">
      <Combobox items={frameworks}>
        <ComboboxInput placeholder="Select a framework" aria-invalid="true" />
        <ComboboxContent>
          <ComboboxEmpty>No items found.</ComboboxEmpty>
          <ComboboxList>
            {(item) => (
              <ComboboxItem key={item} value={item}>
                {item}
              </ComboboxItem>
            )}
          </ComboboxList>
        </ComboboxContent>
      </Combobox>
      <Field data-invalid>
        <FieldLabel htmlFor="combobox-framework-invalid">Framework</FieldLabel>
        <Combobox items={frameworks}>
          <ComboboxInput
            id="combobox-framework-invalid"
            placeholder="Select a framework"
            aria-invalid
          />
          <ComboboxContent>
            <ComboboxEmpty>No items found.</ComboboxEmpty>
            <ComboboxList>
              {(item) => (
                <ComboboxItem key={item} value={item}>
                  {item}
                </ComboboxItem>
              )}
            </ComboboxList>
          </ComboboxContent>
        </Combobox>
        <FieldDescription>Please select a valid framework.</FieldDescription>
        <FieldError errors={[{ message: "This field is required." }]} />
      </Field>
    </div>
  )
}
