// apps/v4/registry/bases/vue/examples/radio-group/RadioGroupInvalid.vue
<script setup lang="ts">
import {
  Field,
  FieldDescription,
  FieldLabel,
  FieldLegend,
  FieldSet,
} from "@/ui/field"
import { RadioGroup, RadioGroupItem } from "@/ui/radio-group"
</script>

<template>
  <FieldSet>
    <FieldLegend>Notification Preferences</FieldLegend>
    <FieldDescription>
      Choose how you want to receive notifications.
    </FieldDescription>
    <RadioGroup default-value="email">
      <Field orientation="horizontal" data-invalid>
        <RadioGroupItem id="invalid-email" value="email" :aria-invalid="true" />
        <FieldLabel html-for="invalid-email" class="font-normal">
          Email only
        </FieldLabel>
      </Field>
      <Field orientation="horizontal" data-invalid>
        <RadioGroupItem id="invalid-sms" value="sms" :aria-invalid="true" />
        <FieldLabel html-for="invalid-sms" class="font-normal">
          SMS only
        </FieldLabel>
      </Field>
      <Field orientation="horizontal" data-invalid>
        <RadioGroupItem id="invalid-both" value="both" :aria-invalid="true" />
        <FieldLabel html-for="invalid-both" class="font-normal">
          Both Email & SMS
        </FieldLabel>
      </Field>
    </RadioGroup>
  </FieldSet>
</template>

// apps/v4/examples/base/radio-group-invalid.tsx
import {
  Field,
  FieldDescription,
  FieldLabel,
  FieldLegend,
  FieldSet,
} from "@/examples/base/ui/field"
import { RadioGroup, RadioGroupItem } from "@/examples/base/ui/radio-group"

export function RadioGroupInvalid() {
  return (
    <FieldSet>
      <FieldLegend>Notification Preferences</FieldLegend>
      <FieldDescription>
        Choose how you want to receive notifications.
      </FieldDescription>
      <RadioGroup defaultValue="email">
        <Field orientation="horizontal" data-invalid>
          <RadioGroupItem value="email" id="invalid-email" aria-invalid />
          <FieldLabel htmlFor="invalid-email" className="font-normal">
            Email only
          </FieldLabel>
        </Field>
        <Field orientation="horizontal" data-invalid>
          <RadioGroupItem value="sms" id="invalid-sms" aria-invalid />
          <FieldLabel htmlFor="invalid-sms" className="font-normal">
            SMS only
          </FieldLabel>
        </Field>
        <Field orientation="horizontal" data-invalid>
          <RadioGroupItem value="both" id="invalid-both" aria-invalid />
          <FieldLabel htmlFor="invalid-both" className="font-normal">
            Both Email & SMS
          </FieldLabel>
        </Field>
      </RadioGroup>
    </FieldSet>
  )
}
