// apps/preview-vue/src/vue/calendar-presets.vue
<script setup lang="ts">
import { ref, type Ref } from 'vue'
import type { DateValue } from '@internationalized/date'
import { getLocalTimeZone, today } from '@internationalized/date'
import { Calendar } from '@/ui/calendar'
import { Button } from '@/ui/button'
import { Card, CardContent, CardFooter } from '@/ui/card'

const date = ref(today(getLocalTimeZone())) as Ref<DateValue>

const presets = [
  { label: 'Today', days: 0 },
  { label: 'Tomorrow', days: 1 },
  { label: 'In 3 days', days: 3 },
  { label: 'In a week', days: 7 },
  { label: 'In 2 weeks', days: 14 },
]

function applyPreset(days: number) {
  date.value = today(getLocalTimeZone()).add({ days })
}
</script>

<template>
  <Card class="mx-auto w-fit max-w-[300px]" size="sm">
    <CardContent>
      <Calendar
        v-model="date"
        class="p-0"
        fixed-weeks
      />
    </CardContent>
    <CardFooter class="flex flex-wrap gap-2 border-t">
      <Button
        v-for="preset in presets"
        :key="preset.days"
        variant="outline"
        size="sm"
        class="flex-1"
        @click="applyPreset(preset.days)"
      >
        {{ preset.label }}
      </Button>
    </CardFooter>
  </Card>
</template>

// apps/v4/examples/react-aria/calendar-presets.tsx
"use client"

import * as React from "react"
import { CalendarDate, getLocalTimeZone, today } from "@internationalized/date"

import { Button } from "@/styles/react-aria-nova/ui/button"
import { Calendar } from "@/styles/react-aria-nova/ui/calendar"
import { Card, CardContent, CardFooter } from "@/styles/react-aria-nova/ui/card"

export function CalendarWithPresets() {
  const [date, setDate] = React.useState<CalendarDate | undefined>(
    new CalendarDate(new Date().getFullYear(), 2, 12)
  )
  const [currentMonth, setCurrentMonth] = React.useState<CalendarDate>(
    new CalendarDate(new Date().getFullYear(), new Date().getMonth() + 1, 1)
  )

  return (
    <Card className="mx-auto w-fit max-w-[300px]" size="sm">
      <CardContent>
        <Calendar
          value={date}
          onChange={setDate}
          focusedValue={currentMonth}
          onFocusChange={setCurrentMonth}
          className="p-0 [--cell-size:--spacing(9.5)]"
        />
      </CardContent>
      <CardFooter className="flex flex-wrap gap-2 border-t">
        {[
          { label: "Today", value: 0 },
          { label: "Tomorrow", value: 1 },
          { label: "In 3 days", value: 3 },
          { label: "In a week", value: 7 },
          { label: "In 2 weeks", value: 14 },
        ].map((preset) => (
          <Button
            key={preset.value}
            variant="outline"
            size="sm"
            className="flex-1"
            onPress={() => {
              const newDate = today(getLocalTimeZone()).add({days: preset.value})
              setDate(newDate)
              setCurrentMonth(newDate)
            }}
          >
            {preset.label}
          </Button>
        ))}
      </CardFooter>
    </Card>
  )
}
