// apps/v4/styles/vue-vega/ui/calendar/CalendarHeader.vue
<script lang="ts" setup>
import { reactiveOmit } from "@vueuse/core"
import type { CalendarHeaderProps } from "reka-ui"
import { CalendarHeader, useForwardProps } from "reka-ui"
import type { HTMLAttributes } from "vue"

import { cn } from "@/lib/utils"

const props = defineProps<
  CalendarHeaderProps & { class?: HTMLAttributes["class"] }
>()

const delegatedProps = reactiveOmit(props, "class")

const forwardedProps = useForwardProps(delegatedProps)
</script>

<template>
  <CalendarHeader
    data-slot="calendar-header"
    :class="
      cn(
        'relative flex w-full items-center justify-center px-8 pt-1',
        props.class
      )
    "
    v-bind="forwardedProps"
  >
    <slot />
  </CalendarHeader>
</template>

// apps/v4/preview-server/src/svelte-ui/calendar/calendar-header.svelte
<script lang="ts">
	import { Calendar as CalendarPrimitive } from "bits-ui";
	import { cn } from "@/svelte-lib/utils.js";

	let {
		ref = $bindable(null),
		class: className,
		...restProps
	}: CalendarPrimitive.HeaderProps = $props();
</script>

<CalendarPrimitive.Header
	bind:ref
	class={cn(
		"flex h-(--cell-size) w-full items-center justify-center gap-1.5 text-sm font-medium",
		className
	)}
	{...restProps}
/>
