// apps/v4/styles/vue-mira/ui/navigation-menu/NavigationMenuIndicator.vue
<script setup lang="ts">
import { reactiveOmit } from "@vueuse/core"
import type { NavigationMenuIndicatorProps } from "reka-ui"
import { NavigationMenuIndicator, useForwardProps } from "reka-ui"
import type { HTMLAttributes } from "vue"

import { cn } from "@/lib/utils"

const props = defineProps<
  NavigationMenuIndicatorProps & { class?: HTMLAttributes["class"] }
>()

const delegatedProps = reactiveOmit(props, "class")

const forwardedProps = useForwardProps(delegatedProps)
</script>

<template>
  <NavigationMenuIndicator
    data-slot="navigation-menu-indicator"
    v-bind="forwardedProps"
    :class="
      cn(
        'cn-navigation-menu-indicator top-full z-[1] flex h-1.5 items-end justify-center overflow-hidden',
        props.class
      )
    "
  >
    <div
      class="cn-navigation-menu-indicator-arrow relative top-[60%] h-2 w-2 rotate-45"
    />
  </NavigationMenuIndicator>
</template>

// apps/v4/preview-server/src/svelte-ui/navigation-menu/navigation-menu-indicator.svelte
<script lang="ts">
	import { NavigationMenu as NavigationMenuPrimitive } from "bits-ui";
	import { cn } from "@/svelte-lib/utils.js";

	let {
		ref = $bindable(null),
		class: className,
		...restProps
	}: NavigationMenuPrimitive.IndicatorProps = $props();
</script>

<NavigationMenuPrimitive.Indicator
	bind:ref
	data-slot="navigation-menu-indicator"
	class={cn(
		"cn-navigation-menu-indicator top-full z-[1] flex h-1.5 items-end justify-center overflow-hidden",
		className
	)}
	{...restProps}
>
	<div class="cn-navigation-menu-indicator-arrow relative top-[60%] h-2 w-2 rotate-45"></div>
</NavigationMenuPrimitive.Indicator>
