// apps/v4/preview-server/src/ui/alert-dialog/AlertDialogMedia.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue"
import { cn } from "@/lib/utils"

const props = defineProps<{
  class?: HTMLAttributes["class"]
}>()
</script>

<template>
  <div
    data-slot="alert-dialog-media"
    :class="cn('cn-alert-dialog-media', props.class)"
  >
    <slot />
  </div>
</template>

// apps/v4/styles/svelte-nova/ui/alert-dialog/alert-dialog-media.svelte
<script lang="ts">
  import { cn, type WithElementRef } from "$lib/utils.js"
  import type { HTMLAttributes } from "svelte/elements"

  let {
    ref = $bindable(null),
    class: className,
    children,
    ...restProps
  }: WithElementRef<HTMLAttributes<HTMLDivElement>> = $props()
</script>

<div
  bind:this={ref}
  data-slot="alert-dialog-media"
  class={cn("cn-alert-dialog-media", className)}
  {...restProps}
>
  {@render children?.()}
</div>
