// apps/v4/registry/bases/svelte/ui/dialog/dialog-header.svelte
<script lang="ts">
	import type { HTMLAttributes } from "svelte/elements";
	import { cn, type WithElementRef } from "$lib/utils.js";

	let {
		ref = $bindable(null),
		class: className,
		children,
		...restProps
	}: WithElementRef<HTMLAttributes<HTMLDivElement>> = $props();
</script>

<div
	bind:this={ref}
	data-slot="dialog-header"
	class={cn("cn-dialog-header flex flex-col", className)}
	{...restProps}
>
	{@render children?.()}
</div>

// apps/v4/registry/bases/vue/ui/dialog/DialogHeader.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue"
import { cn } from "@/lib/utils"

const props = defineProps<{
  class?: HTMLAttributes["class"]
}>()
</script>

<template>
  <div
    data-slot="dialog-header"
    :class="cn('cn-dialog-header flex flex-col', props.class)"
  >
    <slot />
  </div>
</template>
