// apps/preview-vue/src/vue/badge-spinner.vue
<script setup lang="ts">
import { Badge } from '@/ui/badge'
import { Spinner } from '@/ui/spinner'
</script>

<template>
  <div class="flex flex-wrap gap-2">
    <Badge variant="destructive">
      <Spinner data-icon="inline-start" />
      Deleting
    </Badge>
    <Badge variant="secondary">
      Generating
      <Spinner data-icon="inline-end" />
    </Badge>
  </div>
</template>

// apps/v4/examples/radix/badge-spinner.tsx
import { Badge } from "@/examples/radix/ui/badge"
import { Spinner } from "@/examples/radix/ui/spinner"

export function BadgeWithSpinner() {
  return (
    <div className="flex flex-wrap gap-2">
      <Badge variant="destructive">
        <Spinner data-icon="inline-start" />
        Deleting
      </Badge>
      <Badge variant="secondary">
        Generating
        <Spinner data-icon="inline-end" />
      </Badge>
    </div>
  )
}
