// apps/v4/registry/bases/vue/examples/button-group/ButtonGroupWithLike.vue
<script setup lang="ts">
import IconPlaceholder from "@/components/IconPlaceholder.vue"
import { Button } from "@/ui/button"
import { ButtonGroup } from "@/ui/button-group"
import { Example } from "@/components/example"
</script>

<template>
  <Example title="With Like">
    <ButtonGroup>
      <Button variant="outline">
        <IconPlaceholder
          lucide="HeartIcon"
          tabler="IconHeart"
          hugeicons="HeartIcon"
          phosphor="HeartIcon"
          remixicon="RiHeartLine"
          data-icon="inline-start"
        />
        Like
      </Button>
      <Button variant="outline" :as-child="true" size="icon" class="w-12">
        <span>1.2K</span>
      </Button>
    </ButtonGroup>
  </Example>
</template>

// apps/v4/examples/radix/button-group-with-like.tsx
import { Button } from "@/examples/radix/ui/button"
import { ButtonGroup } from "@/examples/radix/ui/button-group"
import { HeartIcon } from "lucide-react"

export function ButtonGroupWithLike() {
  return (
    <ButtonGroup>
      <Button variant="outline">
        <HeartIcon /> Like
      </Button>
      <Button variant="outline" asChild size="icon" className="w-12">
        <span>1.2K</span>
      </Button>
    </ButtonGroup>
  )
}
