// apps/v4/registry/bases/vue/examples/radio-group/RadioGroupWithDescriptions.vue
<script setup lang="ts">
import {
  Field,
  FieldContent,
  FieldDescription,
  FieldLabel,
} from "@/ui/field"
import { RadioGroup, RadioGroupItem } from "@/ui/radio-group"
</script>

<template>
  <RadioGroup default-value="plus">
    <FieldLabel html-for="plus-plan">
      <Field orientation="horizontal">
        <FieldContent>
          <div class="font-medium">
            Plus
          </div>
          <FieldDescription>
            For individuals and small teams
          </FieldDescription>
        </FieldContent>
        <RadioGroupItem id="plus-plan" value="plus" />
      </Field>
    </FieldLabel>
    <FieldLabel html-for="pro-plan">
      <Field orientation="horizontal">
        <FieldContent>
          <div class="font-medium">
            Pro
          </div>
          <FieldDescription>For growing businesses</FieldDescription>
        </FieldContent>
        <RadioGroupItem id="pro-plan" value="pro" />
      </Field>
    </FieldLabel>
    <FieldLabel html-for="enterprise-plan">
      <Field orientation="horizontal">
        <FieldContent>
          <div class="font-medium">
            Enterprise
          </div>
          <FieldDescription>
            For large teams and enterprises
          </FieldDescription>
        </FieldContent>
        <RadioGroupItem id="enterprise-plan" value="enterprise" />
      </Field>
    </FieldLabel>
  </RadioGroup>
</template>

// apps/v4/examples/radix/radio-group-with-descriptions.tsx
import {
  Field,
  FieldContent,
  FieldDescription,
  FieldLabel,
} from "@/examples/radix/ui/field"
import { RadioGroup, RadioGroupItem } from "@/examples/radix/ui/radio-group"

export function RadioGroupWithDescriptions() {
  return (
    <RadioGroup defaultValue="plus">
      <FieldLabel htmlFor="plus-plan">
        <Field orientation="horizontal">
          <FieldContent>
            <div className="font-medium">Plus</div>
            <FieldDescription>For individuals and small teams</FieldDescription>
          </FieldContent>
          <RadioGroupItem value="plus" id="plus-plan" />
        </Field>
      </FieldLabel>
      <FieldLabel htmlFor="pro-plan">
        <Field orientation="horizontal">
          <FieldContent>
            <div className="font-medium">Pro</div>
            <FieldDescription>For growing businesses</FieldDescription>
          </FieldContent>
          <RadioGroupItem value="pro" id="pro-plan" />
        </Field>
      </FieldLabel>
      <FieldLabel htmlFor="enterprise-plan">
        <Field orientation="horizontal">
          <FieldContent>
            <div className="font-medium">Enterprise</div>
            <FieldDescription>For large teams and enterprises</FieldDescription>
          </FieldContent>
          <RadioGroupItem value="enterprise" id="enterprise-plan" />
        </Field>
      </FieldLabel>
    </RadioGroup>
  )
}
