// apps/v4/preview-server/src/svelte/spinner-demo.svelte
<script lang="ts">
	import { Spinner } from "@/svelte-ui/spinner/index.js";
	import * as Item from "@/svelte-ui/item/index.js";
</script>

<div class="flex w-full max-w-xs flex-col gap-4 [--radius:1rem]">
	<Item.Root variant="muted">
		<Item.Media>
			<Spinner />
		</Item.Media>
		<Item.Content>
			<Item.Title class="line-clamp-1">Processing payment...</Item.Title>
		</Item.Content>
		<Item.Content class="flex-none justify-end">
			<span class="text-sm tabular-nums">$100.00</span>
		</Item.Content>
	</Item.Root>
</div>

// apps/v4/examples/radix/spinner-demo.tsx
import {
  Item,
  ItemContent,
  ItemMedia,
  ItemTitle,
} from "@/examples/radix/ui/item"
import { Spinner } from "@/examples/radix/ui/spinner"

export function SpinnerDemo() {
  return (
    <div className="flex w-full max-w-xs flex-col gap-4 [--radius:1rem]">
      <Item variant="muted">
        <ItemMedia>
          <Spinner />
        </ItemMedia>
        <ItemContent>
          <ItemTitle className="line-clamp-1">Processing payment...</ItemTitle>
        </ItemContent>
        <ItemContent className="flex-none justify-end">
          <span className="text-sm tabular-nums">$100.00</span>
        </ItemContent>
      </Item>
    </div>
  )
}
